### ISSUE TITLE
feature requests - windows updates

### ISSUE THREAD

**Issue by nexusofdoom** [bntjah/lancache#1]
lancache-microsoft.conf >

# Windows Updates
server {
        listen lancache-microsoft deferred default;
        server_name microsoft _;
        # DNS entries:
        access_log /srv/lancache/logs/lancache-microsoft-access.log main buffer=128k flush=1m;
        access_log /srv/lancache/logs/lancache-microsoft-keys.log keys_default buffer=128k flush=1m;
        error_log /srv/lancache/logs/lancache-microsoft-error.log;

        # Default Node
        include lancache/resolver;
        include lancache/cache-key-default;

        location / {
                proxy_cache microsoft;
                include lancache/proxy-cache;
        }
}

**Comment by nexusofdoom** [comment]
/etc/ngings/lancache/caches  >

proxy_cache_path /srv/lancache/data/microsoft levels=2:2 keys_zone=microsoft:500m inactive=120d max_size=50000m loader_files=1000 loader_sleep=50ms loader_threshold=300ms;

**Comment by nexusofdoom** [comment]
address=/.windowsupdate.com/0.0.0.0 > did not make a bind file for you I use dnsmasq

**Comment by bntjah** [comment]
Put this is in Development

**Comment by bntjah** [comment]
Doesn't work; just tested it goes over port 8123 so reopening this one till I find a working config!

**Comment by nexusofdoom** [comment]
so windows update is not working for you ?
i have about 50gb of windows update cached on my box 

it should use http port 80

**Comment by nexusofdoom** [comment]
i see that you setup this for DNS 

this is all that i have for my DNS - dnsmasq   "address=/.windowsupdate.com/x.x.x.x"



//
// Add include "/etc/bind/named.local.steam"; to your named.conf.local file
//

zone "windowsupdate.microsoft.com." IN {
        type master;
        file "/etc/bind/db.lancache.microsoft";
};

zone "update.microsoft.com." IN {
        type master;
        file "/etc/bind/db.lancache.microsoft";
};

zone "windowsupdate.com." IN {
        type master;
        file "/etc/bind/db.lancache.microsoft";
};

zone "download.windowsupdate.com." IN {
        type master;
        file "/etc/bind/db.lancache.microsoft";
};

zone "ntservicepack.microsoft.com." IN {
        type master;
        file "/etc/bind/db.lancache.microsoft";
};

**Comment by bntjah** [comment]
Yes, doesn't appear to be working I did how ever made some changes. Have a look over in bind I figure problem is somewhere in there however I see the dns going to the correct ip and the ip reacting but other then that I am unable to detect any updates so might be something I'm looking into tomorrow

Yeah the above list came from https://support.microsoft.com/en-us/kb/818018 (Configure the firewall for software updates)

**Comment by nexusofdoom** [comment]
sounds good . I will be offline tell the jan 9th. going to CES 2016. 
later.

**Comment by bntjah** [comment]
Have a safe trip! And thanks for your help!

**Comment by bntjah** [comment]
Closing this; works after tips from nexusofdoom; merged into development and back into master!
