### ISSUE TITLE
League of Legends CDN Caching

### ISSUE THREAD

**Issue by v3n** [bntjah/lancache#10]
Hi guys,

We enabled SSL on all regions approximately a week ago. Regretfully, it broke local caching for servers. Spoofing an SSL cert won't work as the patcher will reject an invalid cert.

We're aware of the issue and working towards fixing it. You can see a conversation I had with another team about solutions we're investigating here: ti-mo/ansible-lanparty#8

Jonathan Howard // Patcher Team // Riot Venia

**Comment by bntjah** [comment]
Thanks for the update; will follow it on the other github

**Comment by bntjah** [comment]
Temp work around by @v3n (posted in other Issue #[https://github.com/ti-mo/ansible-lanparty/issues/8](url)

> Hi guys,
> 
> Try adding the following line to {League install dir}/RADS/system/system.cfg:
> 
> `UseTLS=false`
> Cheers!
> Jonathan Howard // Riot Venia

**Comment by Stealthii** [comment]
It might be worth closing this issue as the latest released client [has included an HTTP downgrade for RFC1918 (or local IP) addresses](https://github.com/ti-mo/ansible-lanparty/issues/8#issuecomment-199588206). I would suggest a note in documentation about this requirement, but as this instance of lancache has never recommended route poisoning over DNS spoofing, I think we're ok without.
