### ISSUE TITLE
Windows store

### ISSUE THREAD

**Issue by DPCools** [bntjah/lancache#100]
I have noticed to day that installing from the windows store with the lancache in place was giving me errors  i move back  to 1.1.1.1 dns and i was able to install the application from the windows store. has M$ change some thing or is there a fault with the lancache.

**Comment by nexusofdoom** [comment]
What in the windows store was not working do you have the name of the app?
Your location USA, ?
Unbound Config is it current?
What does the logs show?

you can also try this command to see the http traffic and see what the codes show and the location it is pulling from
httpry -i eth0 


note it looks like it working for me 
![image](https://user-images.githubusercontent.com/16519553/39051898-baeaf5e4-446f-11e8-9f31-b1818f7b37ae.png)

New Hosts names maybe?

**Comment by nexusofdoom** [comment]
note I did see one game not work 
downloaded this game new game form store and it pulled 

![image](https://user-images.githubusercontent.com/16519553/39053511-cf803b22-4474-11e8-9351-409e6ec40994.png)

**Comment by nexusofdoom** [comment]
this is one I just had issues with all the other ones did work.
![image](https://user-images.githubusercontent.com/16519553/39053554-f9720a00-4474-11e8-9f2b-850e690c2a42.png)

**Comment by nexusofdoom** [comment]
some of the dns info I can see don't know what they are doing. 
are you signed into the store or not?

![image](https://user-images.githubusercontent.com/16519553/39053695-42e0d1b2-4475-11e8-910b-85dbd68dd18f.png)

**Comment by DPCools** [comment]
I was downloading a app ring.com and amazon music. 
I'm UK and unbound is up to date.

Just tried a game and it worked fine and tried another app and that worked too.

**Comment by nexusofdoom** [comment]
made a ms account and logged into the store and it then worked it downloaded the app
![image](https://user-images.githubusercontent.com/16519553/39059895-6708c260-4485-11e8-8e06-49ebf63ca5d4.png)

**Comment by nexusofdoom** [comment]
this is the DNS settings I have 
## LANcache config ##
    ## Microsoft Windows Updates °|-lc-host-vint:7
        ##### New Added 3/1/2018
        local-zone: "download.microsoft.com." redirect
        local-data: "download.microsoft.com. 600 IN A YOURIP"
        local-zone: "update.microsoft.com.akadns.net." redirect
        local-data: "update.microsoft.com.akadns.net. 600 IN A YOURIP"
        local-zone: "update.microsoft.com.nsatc.net." redirect
        local-data: "update.microsoft.com.nsatc.net. 600 IN A YOURIP"
        #####
        local-zone: "windowsupdate.com." redirect
        local-data: "windowsupdate.com. 600 IN A YOURIP"
        local-zone: "update.microsoft.com." redirect
        local-data: "update.microsoft.com. 600 IN A YOURIP"
        local-zone: "windowsupdate.microsoft.com." redirect
        local-data: "windowsupdate.microsoft.com. 600 IN A YOURIP"
        local-zone: "msxbassets.loris.llnwd.net." redirect
        local-data: "msxbassets.loris.llnwd.net. 600 IN A YOURIP"
        local-zone: "hwcdn.net." redirect
        local-data: "hwcdn.net. 600 IN A YOURIP"
        local-zone: "assets1.xboxlive.com." redirect
        local-data: "assets1.xboxlive.com. 600 IN A YOURIP"
        local-zone: "assets2.xboxlive.com." redirect
        local-data: "assets2.xboxlive.com. 600 IN A YOURIP"
        ######## testing ######
        local-zone: "xboxone.loris.llnwd.net." redirect
        local-data: "xboxone.loris.llnwd.net. 600 IN A YOURIP"
        local-zone: "xboxone.vo.llnwd.net." redirect
        local-data: "xboxone.vo.llnwd.net. 600 IN A YOURIP"
        local-zone: "images-eds.xboxlive.com." redirect
        local-data: "images-eds.xboxlive.com. 600 IN A YOURIP"
        local-zone: "xbox-mbr.xboxlive.com." redirect
        local-data: "xbox-mbr.xboxlive.com. 600 IN A YOURIP"
        local-zone: "assets1.xboxlive.com.nsatc.net." redirect
        local-data: "assets1.xboxlive.com.nsatc.net. 600 IN A YOURIP"
        local-zone: "fullproduct.download.microsoft.com." redirect
        local-data: "fullproduct.download.microsoft.com. 600 IN A YOURIP"
        ########### working ####
        local-zone: "dlassets.xboxlive.com." redirect
        local-data: "dlassets.xboxlive.com. 600 IN A YOURIP"
        local-zone: "tlu.dl.delivery.mp.microsoft.com." redirect
        local-data: "tlu.dl.delivery.mp.microsoft.com. 600 IN A YOURIP"
        #local-zone: "officecdn.microsoft.com." redirect
        #local-data: "officecdn.microsoft.com. 600 IN A YOURIP"
        local-zone: "officecdn.microsoft.com.edgesuite.net." redirect
        local-data: "officecdn.microsoft.com.edgesuite.net. 600 IN A YOURIP"
        #local-zone: "nexus.officeapps.live.com." redirect
        #local-data: "nexus.officeapps.live.com. 600 IN A YOURIP"
        #local-zone: "mp.microsoft.com." redirect
        #local-data: "mp.microsoft.com. 600 IN A YOURIP"

**Comment by DPCools** [comment]
Mine 

     ## Microsoft Windows Updates °|-lc-host-vint:7
        local-zone: "windowsupdate.com." redirect
        local-data: "windowsupdate.com. 600 IN A My IP"
        ############################ added 09/03/2018 #######################
        local-zone: "download.microsoft.com." redirect
        local-data: "download.microsoft.com. 600 IN A My IP"
        local-zone: "update.microsoft.com.akadns.net." redirect
        local-data: "update.microsoft.com.akadns.net. 600 IN A My IP"
        local-zone: "update.microsoft.com.nsatc.net." redirect
        local-data: "update.microsoft.com.nsatc.net. 600 IN A My IP"
        #####################################################################
        local-zone: "dlassets.xboxlive.com." redirect
        local-data: "dlassets.xboxlive.com. 600 IN A My IP"
        local-zone: "msxbassets.loris.llnwd.net." redirect
        local-data: "msxbassets.loris.llnwd.net. 600 IN A My IP"
        local-zone: "xboxone.loris.llnwd.net." redirect
        local-data: "xboxone.loris.llnwd.net. 600 IN A My IP"
        local-zone: "xboxone.vo.llnwd.net." redirect
        local-data: "xboxone.vo.llnwd.net. 600 IN A My IP"
        local-zone: "images-eds.xboxlive.com." redirect
        local-data: "images-eds.xboxlive.com. 600 IN A My IP"
        local-zone: "xbox-mbr.xboxlive.com." redirect
        local-data: "xbox-mbr.xboxlive.com. 600 IN A My IP"
        local-zone: "assets1.xboxlive.com.nsatc.net." redirect
        local-data: "assets1.xboxlive.com.nsatc.net. 600 IN A My IP"
        local-zone: "assets1.xboxlive.com." redirect
        local-data: "assets1.xboxlive.com. 600 IN A My IP"
        local-zone: "assets2.xboxlive.com." redirect
        local-data: "assets2.xboxlive.com. 600 IN A My IP"
        local-zone: "fullproduct.download.microsoft.com." redirect
        local-data: "fullproduct.download.microsoft.com. 600 IN A My IP"
        local-zone: "lcy.llnw.net." redirect
        local-data: "lcy.llnw.net. 600 IN A My IP"
        local-zone: "lon.llnw.net." redirect
        local-data: "lon.llnw.net. 600 IN A My IP"
        #######################Added 09/03/2018 ############################
        local-zone: "tlu.dl.delivery.mp.microsoft.com." redirect
        local-data: "tlu.dl.delivery.mp.microsoft.com. 600 IN A My IP"
        local-zone: "officecdn.microsoft.com." redirect
        local-data: "officecdn.microsoft.com. 600 IN A My IP"
        local-zone: "officecdn.microsoft.com.edgesuite.net." redirect
        local-data: "officecdn.microsoft.com.edgesuite.net. 600 IN A My IP"
        local-zone: "hwcdn.net." redirect
        local-data: "hwcdn.net. 600 IN A My IP"
        local-zone: "windowsupdate.microsoft.com." redirect
        local-data: "windowsupdate.microsoft.com. 600 IN A My IP"
        ####################################################################

**Comment by DPCools** [comment]
From the looks of it it might have been that time of day. i have down loaded lots now and it looks to be fine.

**Comment by nexusofdoom** [comment]
ok so we can close this ticket?

**Comment by DPCools** [comment]
Yes we can
