### ISSUE TITLE
A few more domains

### ISSUE THREAD

**Issue by billthecatt** [bntjah/lancache#114]
Along with the gamers, come their shiny ithings and they can make for a nice DDOS on the internet connection if FB happens to put out a large update and 10 or more of your attendees happen to have an iphone.. Its not the gigs worth of bandwidth that you get caching a game CDN but I've been saving a few gig here and there with the following additions to the apple section of my unbound.conf:

        local-zone: "swdownload.apple.com." redirect
        local-data: "swdownload.apple.com. 600 IN A 10.1.1.21"
        local-zone: "aaplimg.com." redirect
        local-data: "aaplimg.com. 600 IN A 10.1.1.21"
        local-zone: "iosapps.itunes.apple.com." redirect
        local-data: "iosapps.itunes.apple.com. 600 IN A 10.1.1.21"

All three of these appear to support iOS type devices such as iphones and I've not been having issues otherwise.

Additionally here are a few steam domains that appear to be working correctly now:

        local-zone: "steamcdn-a.akamaihd.net." redirect
        local-data: "steamcdn-a.akamaihd.net. 600 IN A 10.1.1.11"
        local-zone: "media4.steampowered.com." redirect
        local-data: "media4.steampowered.com. 600 IN A 10.1.1.11"
        local-zone: "media2.steampowered.com." redirect
        local-data: "media2.steampowered.com. 600 IN A 10.1.1.11"
        local-zone: "clientconfig.akamai.steamstatic.com." redirect
        local-data: "clientconfig.akamai.steamstatic.com. 600 IN A 10.1.1.11"

Guessing media1,3,5 exist, but I haven't yet seen them in the squid logs so... I'll wait and see. clientconfig didn't work previously, but seems to work without issue now. Perhaps my sniproxy is just working overtime, but the on disk cache size is steadily growing so.. 

All of the CDNs appear to be in flux at the moment, hope these help someone else.

**Comment by bntjah** [comment]
Added these in commit 924b598  ;-)
Closing it here
