### ISSUE TITLE
cdn.blizzard.com

### ISSUE THREAD

**Issue by fasa1977** [bntjah/lancache#120]
Hi! I am using mikrotik as DNS server, all DNS entries are working ok except cdn.blizzard.com, as soon I activate this DNS, battle net stops uptating (I am testing with SC II)
Hope someone can help me on this, thanks in advance

**Comment by billthecatt** [comment]
Seems to me like your sniproxy must be broken and not correctly handling the SSL requests that go to cdn.blizzard.com. Just my guess, but I'd walk thru the install for that section of code and make sure it's configured properly. Mine was broken for a lil and everything else (steam, microsoft) worked correctly except blizzard, who has mixed http/https content on their servers.

**Comment by fasa1977** [comment]
> Seems to me like your sniproxy must be broken and not correctly handling the SSL requests that go to cdn.blizzard.com. Just my guess, but I'd walk thru the install for that section of code and make sure it's configured properly. Mine was broken for a lil and everything else (steam, microsoft) worked correctly except blizzard, who has mixed http/https content on their servers.

Thanks! since when Blizzard needs https? never needed to install SNIProxy, now I made a fresh install (lost my caches t.t) I did't know about this...

**Comment by fasa1977** [comment]
Fixed with a fresh install
