### ISSUE TITLE
Ubuntu 18

### ISSUE THREAD

**Issue by fasa1977** [bntjah/lancache#125]
Hi!, trying to install the lancache on Ubuntu 18.04.1 LTS and the package libgd2-xpm-dev is not found, it seems that last compatibility of this package was Ubuntu 14.04.5 LTS, any replacement, is it totally necessary?

**Comment by elico** [comment]
@fasa1977 I am pretty sure that it was renamed to `libgdchart-gd2-xpm-dev`

**Comment by fasa1977** [comment]
Thanks !
Also in: Disable IPv6
		echo "net.ipv6.conf.all.disable_ipv6=1" >/etc/sysctl.d/disable-ipv6.conf
    		sysctl -p /etc/sysctl.d/disable-ipv6.conf
how can be done in U18?

**Comment by fasa1977** [comment]
> Thanks !
> Also in: Disable IPv6
> echo "net.ipv6.conf.all.disable_ipv6=1" >/etc/sysctl.d/disable-ipv6.conf
> sysctl -p /etc/sysctl.d/disable-ipv6.conf
> how can be done in U18?
