### ISSUE TITLE
docs need updating

### ISSUE THREAD

**Issue by billthecatt** [bntjah/lancache#134]
The part that creates folders is missing both apple and blizzard folder creation??!?!? Is this intentional or an oversight?

also the sniproxy tests appear to want tcpdump installed so we really should add 

apt-get install tcpdump 

to the prereqs section to get this part work work without fail. perhaps it's there on ubuntu but it was missing from my fresh deb 9.6 install soo...

**Comment by bntjah** [comment]
Added :)
