### ISSUE TITLE
IDEA: Switch from full zones to RPZ

### ISSUE THREAD

**Issue by dhoffend** [bntjah/lancache#16]
We're preparing our servers for our party as well. I'm currently playing with a alternative way to actually redirect users to the lancache server. Maybe the idea is worth some thoughts

The idea is to use the RPZ (Response Policy Zone) feature from bind. RPZ is basically a DNS Firewall where you can modify, redirect or block dns queries/results. All rules are basically stored in a normal zone which replicated across nameservers. It support single hosts and even wildcards.

1) Create a local zone definition

```
zone "rpz.example.net" {
        type master;
        file "/etc/bind/db.rpz.example.net";
};
```

2) load the RPZ zone in the options { } section

```
response-policy {zone "rpz.example.net";};
```

3) fill it with content

```
$TTL 2h ; default TTL
$ORIGIN rpz.example.net.
@       SOA     ns1.example.net. admin.example.net. (
                1          ; serial
                604800     ; refresh (1 week)
                86400      ; retry (1 day)
                2419200    ; expire (4 weeks)
                86400      ; minimum (1 day)
                )
        NS      ns1.example.net.
        NS      ns2.example.net.

cs.steampowered.com                     CNAME lancache-steam.example.net.
*.cs.steampowered.com                   CNAME lancache-steam.example.net.
content1.steampowered.com               CNAME lancache-steam.example.net.
content2.steampowered.com               CNAME lancache-steam.example.net.
content3.steampowered.com               CNAME lancache-steam.example.net.
content4.steampowered.com               CNAME lancache-steam.example.net.
content5.steampowered.com               CNAME lancache-steam.example.net.
content6.steampowered.com               CNAME lancache-steam.example.net.
content7.steampowered.com               CNAME lancache-steam.example.net.
content8.steampowered.com               CNAME lancache-steam.example.net.
content9.steampowered.com               CNAME lancache-steam.example.net.
*.hsar.steampowered.com.edgesuite.net   CNAME lancache-steam.example.net.
*.akamai.steamstatic.com                CNAME lancache-steam.example.net.
content-origin.steampowered.com         CNAME lancache-steam.example.net.
```

I can't tell you anything about performance hits, but maybe it's worth a look. Maybe bind logging has to be adjusted but well ...

p.s. check the minimum required bind version (9.8). I know debian8 works, but the best version for it would be 9.10+. The RPZ feature is usually used to block dns requests to domains that contain bad stuff like trojaner and such.

**Comment by bntjah** [comment]
Great idea; but this feels very similar to what we are doing now... since we don't need to define for example content1 to content9 since everything below steampowered.com is also taking to lancache-steam.example.net

**Comment by cerealcable** [comment]
I'm a fan of the PRZ style since its much more granular than just doing a
zone redirect on steampowered.com which means its less likely to need to
proxy content that isn't content related. I'll probably look into doing
this for my next event personally, it looks much more flexible for our
needs (we also block additional sites so this is much easier than what
we've done in the past).

Morgan Humes

**Comment by bntjah** [comment]
I feel that this is implemented through unbound; but correct me if I'm wrong...

**Comment by fhibler** [comment]
@dhoffend Can you check out the unbound config we added to the latest commits? Thx and glad to see you again :)

**Comment by bntjah** [comment]
Closing it as no feedback since January ...

**Comment by dhoffend** [comment]
Sorry. I'm not using unbound therefore I can't comment on it.

We're using a bind setup where the RPZ zone is syncronized between both DNS servers (master/slave) as well as the Dyndns integration between isc-dhcpd/bind.

When I opened this request the project was still using bind afaik. The idea was targeted to provide a more easier and granular approach of hijack DNS resolvings :-) but since you've switch to unbound the bind RPZ idea is no longer useful (only to those that don't wanna use unbound) maybe some notes in the readme would be beneficial to those that prefer alternative setups.

This project provides a great source for lancache setups (nginx setup and zones) but not everyone is using the same infrastructure services (unbound vs bind) ... anyway ...

Good look and keep the project running.
