### ISSUE TITLE
please i neeed help to add gameloop host in the server to cache gameloop download contents , please i need help 

### ISSUE THREAD

**Issue by ArvinMeyer** [bntjah/lancache#163]
please i neeed help to add gameloop host in the server to cache gameloop download contents , please i need help

**Comment by hazemhagrass** [comment]
Same problem here

**Comment by ArvinMeyer** [comment]
i have resolve this problem i can help you

**Comment by ArvinMeyer** [comment]
> Same problem here

i have resolve this problem i can help you

**Comment by nagilum99** [comment]
If you resolved it, you could make a pull request and submit your changes. That's what brings OSS to life!
