### ISSUE TITLE
feature requests - tera

### ISSUE THREAD

**Issue by nexusofdoom** [bntjah/lancache#2]
# Tera Game Updates
server {
        listen lancache-tera deferred default;
        server_name tera _;
        # DNS entries:
        access_log /srv/lancache/logs/lancache-tera-access.log main buffer=128k flush=1m;
        access_log /srv/lancache/logs/lancache-tera-keys.log keys_default buffer=128k flush=1m;
        error_log /srv/lancache/logs/lancache-tera-error.log;

        # Default Node
        include lancache/resolver;
        #include lancache/cache-key-default;

        location / {
                proxy_cache tera;
                proxy_set_header Range $http_range;
                proxy_set_header If-Range $http_if_range;
                proxy_cache_key "$server_name$request_uri $http_range";
                proxy_cache_valid 206 90d;
                include lancache/proxy-cache;
        }
}

**Comment by nexusofdoom** [comment]
/etc/nginx/lancache/cache > 

proxy_cache_path /srv/lancache/data/tera levels=2:2 keys_zone=tera:500m inactive=120d max_size=50000m loader_files=1000 loader_sleep=50ms loader_threshold=300ms;

**Comment by nexusofdoom** [comment]
address=/patch.tera.enmasse-game.com/0.0.0.0 = your IP  > need to make a bind file i use firewall rules to do this

**Comment by bntjah** [comment]
Put this is in Development Branch
