### ISSUE TITLE
Xbox One Caching

### ISSUE THREAD

**Issue by 3guk** [bntjah/lancache#24]
Was just wondering if you knew of anyone that managed to get Xbox one caching working, not too fussed about game updates, would really like to know if you can cache system updates this way ?

**Comment by imac2009** [comment]
I think this could be possible by gathering MS CDN's, may it be done by sniffing yourself - or some one else who can provide this info. Unfortunately I don't have access to a XBONE nor do I know someone around who could provide it.

**Comment by bntjah** [comment]
In the same boat as iMac here; don't have a XBONE; but as long as it happens over HTTP I can say it can be cached; just need to redirect the correct DNS to the Lancache and should work fine...

**Comment by bntjah** [comment]
@3guk I've seen your post on reddit and added the DNS links to the unbound; so would need testing...

**Comment by bntjah** [comment]
@3guk do you happen to have an update? If not I'm closing this issue by the end of the week as we don't have any means of testing it...

If any one else is inclined to test this please let us know as it would be handy for future events that we get this working...

**Comment by bntjah** [comment]
Didn't hear anything back; so closing this
