### ISSUE TITLE
Caching Issue with Blizzard

### ISSUE THREAD

**Issue by raz3r83** [bntjah/lancache#26]
First of all awesome work with the caching server and making it so much simple to install and get setup, many thanks to all contributors.

Onto the issue, the caching server has been setup on Debian using the lc_installer.sh script and is using unbound installed to the same server for DNS, both steam and origin are caching great.

The DNS redirect for blizzard is working and I can see the traffic is going through the cache, I can see available disk space reducing as it caches blizzard content, however re-installed a game that should be cached pulls all data through from the internet again.

Tested with all but Overwatch from the blizzard downloader.

I was receiving a large number of errors in the log about not being able to resolve host, however a ping from that server resolves correctly, whereas a ping from a machine local to the network resolves to the blizzard virtual interface.

Any help/advice for tracking this down would be much appreciated.

**Comment by bntjah** [comment]
Hey @raz3r83 will give this a test myself somewhere this week.

@nexusofdoom did you happen to run in to these issues?

**Comment by raz3r83** [comment]
Hi @bntjah sorry only just saw your response, I don't think that entry is in my unbound config will give it a try tonight and report back.

**Comment by raz3r83** [comment]
Hi @bntjah Just had a few minutes at work so checked the unbound conf and I have already got that address in there.

**Comment by bntjah** [comment]
I'll try and have a look on my setup what it does there

**Comment by nexusofdoom** [comment]
testing on mine now with this list of domains 

address=/edge.blizzard.top.comcast.net/10.0.4.24
		address=/level3.blizzard.com/10.0.4.24    
		address=/blzddist1-a.akamaihd.net/10.0.4.24
		address=/blzddist1-b.akamaihd.net/10.0.4.24
		address=/blzddist2-a.akamaihd.net/10.0.4.24
		address=/blzddist2-b.akamaihd.net/10.0.4.24
		address=/blzddist3-a.akamaihd.net/10.0.4.24
		address=/blzddist3-b.akamaihd.net/10.0.4.24

**Comment by nexusofdoom** [comment]
the game "Overwatch" looks like it is using torrnet or other servers to get updates 
still looking into it

**Comment by raz3r83** [comment]
hmmm edge.blizzard.top.comcast.net doesn't appear to be in the unbound config for blizzard.

**Comment by bntjah** [comment]
@raz3r83 wasn't aware that it existed; so updated the unbound config with it

**Comment by raz3r83** [comment]
Right so i can only apologize profusely as taking the caching server over to a friends for testing with the new Firewall setup and blizzard appears to have served it's cached content perfectly fine.

I still have no idea as to why when I first tested it the content went through the cache but testing pulled from the internet again, regardless it worked exactly as expected last night.

At this moment i have Steam, Origin, Uplay and Blizzard tested and working, Wargaming doesn't seem to work but not many people play that at the LAN this is for.

So a new entry for the unbound.conf, and sorry i should have tested more thoroughly it seems. :(

If you want to mark this as closed now please do.

**Comment by imac2009** [comment]
This the way of making progress and learning stuff ;) But you can't just leave without providing info about your LAN since bn and me are big fans of in general !

**Comment by raz3r83** [comment]
It's a fairly small LAN of 48 focused more on having fun than competitive gaming near Sheffield, https://lanops.co.uk/ it will be interesting to see how just how much bandwidth it can save us this LAN, as its been loaded with around 1TB of data. The caching server has undergone a number of different iterations trying to find the best config from virtualised, bare metal using Ubuntu and even a config based on FreeBSD, I'm pretty happy with it this time though.

We do have a few tickets left if you fancy it and have this weekend free :) (shameless plug 👍 )

**Comment by bntjah** [comment]
Its to bad that I don't have any time this weekend or I might have taken you up on this idea of a lan in UK ...  :-( perhaps next time! :-)

Good luck though!

For the LAN I run its a VM with ZFS Striped on 2 datastores (2x Samsung EVO 850 500GB) and 4 or 8 GB of ram (I'm not 100% sure and unable to check atm) and 2 vcpu assigned from a i5 2500k
O/S is Debian
