### ISSUE TITLE
Out of order IP addresses on Interfaces

### ISSUE THREAD

**Issue by travispk** [bntjah/lancache#31]
Is there a reason why the IP address are completely out of order and different on the installer.sh compared to the manual install?  I'd love to see the IP address in order in the interfaces and host file.  Maybe it is just my OCD kicking in.  Was going to do a pull request, but wasn't sure if there was a reason behind.

Short example:

**installer.sh - interface file**

    # IP used for Steam caching
    auto eth0:1
    iface eth0:1 inet static
    address 10.10.10.68
    netmask 255.255.255.0

    # IP used for Riot caching
    auto eth0:2
    iface eth0:2 inet static
    address 10.10.10.67
    netmask 255.255.255.0

    # IP used for Blizzard caching
    auto eth0:3
    iface eth0:3 inet static
    address 10.10.10.62
    netmask 255.255.255.0

**Manual install - interface file**

    # Ip used for STEAM caching
    auto eth0:1
    iface eth0:1 inet static
    address 10.10.10.61
    netmask 255.255.255.0

    # Ip used for RIOT caching
    auto eth0:2
    iface eth0:2 inet static
    address 10.10.10.62
    netmask 255.255.255.0

    # Ip used for Blizzard caching
    auto eth0:3
    iface eth0:3 inet static
    address 10.10.10.63
    netmask 255.255.255.0

**Comment by bntjah** [comment]
Not really an idea why might have happened due to using different configs from time to time and forgetting to use a uniform; so will change this later on. Thanks for bringing to my attention

**Comment by bntjah** [comment]
Seems to be fixed by TravisPK latest merge so will close this
