### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by travispk** [bntjah/lancache#33]
I'd recommend adding a good description on this repo so that it ranks better in search engines.

**Comment by bntjah** [comment]
Feel free to give your thoughts; as its only was a side project for me when I started doing this and it kind of evolved to this ;-)

**Comment by travispk** [comment]
Indeed.  After my LAN Party this weekend I'll put some thoughts into that and more documentation.  Just spent the last 4 hours working on the recent updates I just submitted for pull requests. It's now 2am and I need to go to bed, we are setting up for the event tomorrow night... :)

Take care

**Comment by bntjah** [comment]
All I can say is... Thanks! and Good luck! :-)
To bad your event is on the other side of the ocean ;-) other wise might have considered to come over ;-)

**Comment by travispk** [comment]
Sounds good.  

I just released my gamebridge solution to the world.  I'll need to make an installer like you did, right now it is manual steps.
https://github.com/travispk/gamebridge

**Comment by travispk** [comment]
How about this for description:

Improve download speeds and reduce strain on your Internet connection at LAN parties.  Locally cache game installs and updates from the largest distributors: Steam, RIOT, Blizard, Hirez, Origin, Sony, Microsoft, Tera, GOG, ArenaNetworks, WarGaming, and Uplay.

Super easy to setup with auto installer script!

**Comment by travispk** [comment]
I'd go with that description.  It can always be updated later.

**Comment by bntjah** [comment]
Will be Added; will be changed if deemed necessary

**Comment by travispk** [comment]
Looks like this lancache has moved way up in Google now with the new description. ;)  I see it as #2 in my organic list when searching for lancache.  Woot!
