### ISSUE TITLE
Slicing and proxy_bind

### ISSUE THREAD

**Issue by ekhoury2000** [bntjah/lancache#35]
Hi @bntjah 

does this option (--with-http_slice_module) means slicing would be enabled?  wouldnt this affect riot League of legends? or is it working fine? also, i could not find where to change to proxy_bind variable? is it in /usr/local/nginx/conf/nginx.conf ? cz i cant see it there.

also, anyone tested with blizzard games?

Thanks,

**Comment by bntjah** [comment]
HI @ekhoury2000,

this means that you compiled nginx with slicing meaning that if defined in the configs it can be used for slicing. We have run the config as you can find it here last time on Guns-N-Bits in October 2016 so if they didn't change the DNS to much it should remain the same. Correct me if I'm wrong here @imac2009 but you didn't change anything or not to big of changes (except for ip addresses)?

Changing the proxy_bind variable can be done within each config seperatly within /usr/local/nginx/conf/vhosts-enabled/*.conf
For example lancache-riot.conf would be line #17...

As far as I tested it works with Blizzard Games just fine as long as they don't switch to HTTPS as Riot did a while back and then reverted to HTTP...

Geoffrey

**Comment by ekhoury2000** [comment]
@bntjah Thank you for your prompt reply.
as far as i understood, i will then change  lc-host-proxybind value to 192.168.1.1 for example.

also i will test on all games and let you know,

Thanks again

**Comment by bntjah** [comment]
@ekhoury2000 I wouldn't put it on 192.168.1.1 as this is the ip of your gateway.
You should put the ip there of the eth interface that your lancache box is using... not the gateway ;-)

Do let me know how it worked out for you, and no problem we are only here to try and help each other out ;-)

Geoffrey

**Comment by ekhoury2000** [comment]
@bntjah yea i know :) thanks again.

i have tested many lancache but none worked, they all worked fine for couple of games or for game downloads but not game updates, and some crashed games when client update was found(riot).
i have excluded steam from interfaces since i am using a different server for steamcache.
  i hope this will work for me now, thanks again

**Comment by bntjah** [comment]
@ekhoury2000 the tricky part is keeping it up to date; it might be possible that not all games would work here as its alot of different company's with their own vision but we try to keep it going for the most games (the ones used at a lan) but we can't make any promises...

Do let me know if this satisfies your demands; and if you have any problems let us know and we'll try to help you asap!

Geoffrey

**Comment by ekhoury2000** [comment]
hi again @bntjah 
i ran into the error while running : ./autogen.sh && ./configure && make check && sudo make install
./setver.sh: 35: ./setver.sh: debchange: not found
./autogen.sh: 5: ./autogen.sh: autoreconf: not found

Any suggestions?

Thanks

**Comment by bntjah** [comment]
Hi @ekhoury2000 
If I read the error correctly I'm suspecting you receive this error with configuring SNIproxy?
https://github.com/dlundquist/sniproxy/issues/188 tells me you should do the following: sudo apt-get install devscripts allthough loads extra software that I don't think you actually need this seems to fix it... 
But is a bith unclear from your error...

**Comment by ekhoury2000** [comment]
Thanks @bntjah  that fixed it, i also used sudo apt-get install autoconf to fix the whole thing. but now, running  (./autogen.sh && ./configure && make check && sudo make install) gave the below errors at the end (donno if it's a big deal):
./configure: line 4506: syntax error near unexpected token `LIBEV,'
./configure: line 4506: `PKG_CHECK_MODULES(LIBEV, libev, HAVE_LIBEV=yes; $as_echo "#define HAVE_LIBEV 1" >>confdefs.h'

and i cannot start sniproxy, ( ./sniproxy -c /etc/sniproxy.conf 
-bash: ./sniproxy: Is a directory) . appreciat your help :)

**Comment by bntjah** [comment]
@ekhoury2000 did you chmod +x sniproxy ? As I think its not executable and this is giving you this error...

**Comment by ekhoury2000** [comment]
@bntjah  where is the file supposed to be located? i have the lib sniproxy clone to the root dir and everything from there as root.
Thanks

**Comment by bntjah** [comment]
@ekhoury2000 I think that will be: chmod +x /sniproxy/sniproxy and to run it ./sniproxy/sniproxy -c /etc/sniproxy.conf

This is as based on what I understand from your input here ;-)

**Comment by ekhoury2000** [comment]
@bntjah actually i cannot find the sniproxy executable :( should there be a library called sniproxy somewhere other than the clone? sorry i know these are basics for you, appreciate ur patience

**Comment by bntjah** [comment]
@ekhoury2000 please walk me through the commands / steps you done. :-) 
Everybody has to learn somewhere, so don't worry :-) we will get there eventually ;-)

**Comment by ekhoury2000** [comment]
@bntjah thanks a lot 👍 i ran the below step by step after a sudo -i, i was placed at root dir:
14) Install sniproxy for passing through HTTPS traffic (cannot be cached)
	14.1) git clone https://github.com/dlundquist/sniproxy
	14.2) sudo curl https://raw.githubusercontent.com/OpenSourceLAN/origin-docker/master/sniproxy/sniproxy.conf -o /etc/sniproxy.conf
	19.3) cd sniproxy 
          19.3.1) sudo apt-get install devscripts
          19.3.2) sudo apt-get install autoconf
	19.4) ./autogen.sh && ./configure && make check && sudo make install (got the error above mentioned in previous comment)
	19.5) ran the command : 
                 ./sniproxy -c /etc/sniproxy.conf

**Comment by bntjah** [comment]
@ekhoury2000 so if I basicly understand this correctly you are currently sitting in /sniproxy with your shell ?
So would be something like username@machine: /sniproxy$ ?
From what I understand try the following:
1) cd /sniproxy
2) chmod +x sniproxy
3) ./sniproxy -c /etc/sniproxy.conf

**Comment by ekhoury2000** [comment]
@bntjah 
root@GPROXY:/sniproxy# chmod +x sniproxy
chmod: cannot access 'sniproxy': No such file or directory
 :(

**Comment by bntjah** [comment]
@ekhoury2000 can you give me the output from ls ?

**Comment by ekhoury2000** [comment]
@bntjah 
root@GPROXY:/sniproxy# ls
aclocal.m4       autom4te.cache  config.rpath  debian      m4           missing    redhat         test-coverage
ARCHITECTURE.md  ChangeLog       configure     depcomp     Makefile.am  NEWS       setver.sh      test-driver
AUTHORS          compile         configure.ac  INSTALL     Makefile.in  README     sniproxy.conf  tests
autogen.sh       config.log      COPYING       install-sh  man          README.md  src            TODO

**Comment by bntjah** [comment]
@ekhoury2000 I think I'm giving you wrong information; since I'm not sitting behind my setup (currently @ work) but you can currently skip the sniproxy step for configuring / testing as it will only pass through https traffic so due note that https traffic won't work untill I get behind my setup

**Comment by ekhoury2000** [comment]
@bntjah Ok i get it, i can give u teamviewer if that's ok with you, otherwise, i will wait until u have free time abd reply, Thanks a lot for your time really appreciate it

**Comment by bntjah** [comment]
Hey @ekhoury2000 that won't be possible untill I get home... Feel free to send me a mail geoffrey.vanwiele@gmail.com and we will pick it up there ;-)

**Comment by bntjah** [comment]
Closing this issue; as I'm going to help @ekhoury2000 through other channels :-)

**Comment by DonatelloXX** [comment]
I have the same error like ekhoury2000. When running ./configure i get this output at the end:

./configure: line 4506: syntax error near unexpected token LIBEV,' ./configure: line 4506:PKG_CHECK_MODULES(LIBEV, libev, HAVE_LIBEV=yes; $as_echo "#define HAVE_LIBEV 1" >>confdefs.h'

btw: before i could use autogen.sh i needed to `apt install devscripts`

**Comment by DonatelloXX** [comment]
Ah - found a solution in lc-installer on line 231

sudo apt-get install libudns0 libudns-dev libev4 libev-dev devscripts automake libtool autoconf autotools-dev cdbs debhelper dh-autoreconf dpkg-dev gettext  pkg-config fakeroot -y

**Comment by dark-swordsman** [comment]
@bntjah Can "Changing the proxy_bind variable can be done within each config seperatly within /usr/local/nginx/conf/vhosts-enabled/*.conf"

Be added to step 10 in the current manual install doc? It's very confusing.

**Comment by bntjah** [comment]
@Kyle it could but I haven't looked at the install doc for a while.
If you could try and clarify what is confusing we'll try and tidy it up and
clarify what isn't clear atm.
But to answer your question: yes for now it needs to be done in each config
seperately. This way you could use assign a different interface and spread
the load abith...


Op di 26 mrt. 2019 om 01:53 schreef Kyle Barr <notifications@github.com>:
