### ISSUE TITLE
OSX Apple Updates?

### ISSUE THREAD

**Issue by nexusofdoom** [bntjah/lancache#36]
do we want to have OSX Apple Updates to be added to lancache?
I am going to be testing in my test setup in the next few weeks.

**Comment by bntjah** [comment]
Hey Nexus, would always be handy...
Not that I'm expecting much OSX devices to turn up on a lan might be interesting as it makes lancache more usable outside lan's so yes I would be interested...

I think @imac2009 can do some testing aswell since I know he has a few mac's ;-)

**Comment by nexusofdoom** [comment]
attached is some names servers for apple 
![img_20170404_125020](https://cloud.githubusercontent.com/assets/16519553/24671311/b0b4fcf6-1936-11e7-83e1-dd3bf7ba6dcb.jpg)

**Comment by nexusofdoom** [comment]
more on the dns names

https://support.apple.com/en-us/HT202943

Server addresses used by Software Update

Software Update must communicate with Apple's update servers in order to download and install updates. Ask your network administrator to allow the following server addresses on your DNS and proxy servers.
swcdn.apple.com
swdownload.apple.com
swquery.apple.com
swscan.apple.com
Software Update communicates with these servers using TCP port 80 or 443 depending on your version of OS X, as well as dynamic and/or private ports 49152 through 65535.

**Comment by fhibler** [comment]
I am really just wondering if Apple's Cache solution (integrated in the OSX Server.app) might be more efficient for connected clients. Apple seeds from a various of different servers (incl. Akamai, etc.). This would iOS, macOS, Apps, iCloud (if wanted).

Also a lot of traffic would be HTTPS as far I understood. What do you think?

**Comment by bntjah** [comment]
While this is interesting since there is most likely an osx server app somewhere out there and no one really beeing able to answer this...
And I don't recall seeing alot of Mac users on a lan... I think its safe to safe we can close this?

**Comment by fhibler** [comment]
+1

**Comment by nexusofdoom** [comment]
In the coming weeks I will be testing the osx updates and post what I
find.  This can be used more then just for lan party's it can be used for
repair shops or places with limited internet access. So it does have lots
of places that osx caching can be useful.

**Comment by imac2009** [comment]
Afaik speaking of caching AppStore or iTunes purchases for let's say deploying software to corporate mobile iDevices the only way to go is via MacOS Server.

Fun fact: mass deployment for iOS actually was bringing me into this project, but I never really investigated it.

But if it comes in handy I do have all HW to eventually do some tests if needed.

Let's close it for the moment and get back to it at some point.

**Comment by nexusofdoom** [comment]
I will update this ticket when done testing in our lab.  Thanks.

**Comment by nexusofdoom** [comment]
well started early today and its caching OSX updates!
![p_20170428_151425_1_p](https://cloud.githubusercontent.com/assets/16519553/25545805/fd3e1376-2c25-11e7-849f-7610f149b6a2.jpg)
![p_20170428_151530_1_p](https://cloud.githubusercontent.com/assets/16519553/25545809/01acd73a-2c26-11e7-817b-8981205143e5.jpg)
![p_20170428_151430_1_p](https://cloud.githubusercontent.com/assets/16519553/25545818/09f13a44-2c26-11e7-9e36-83e8442029a3.jpg)

**Comment by nexusofdoom** [comment]
#unbound config  
## OSX Updates °|-lc-host-vint:x
        local-zone: "mzstatic.com." redirect
        local-data: "mzstatic.com. 600 IN A x.x.x.x"
        local-zone: "swcdn.apple.com." redirect
        local-data: "swcdn.apple.com. 600 IN A x.x.x.x"
        local-zone: "itunes-apple.com." redirect
        local-data: "itunes-apple.com. 600 IN A x.x.x.x"
        local-zone: "swscan.apple.com." redirect
        local-data: "swscan.apple.com. 600 IN A x.x.x.x"

**Comment by nexusofdoom** [comment]
[lancache-osx.txt](https://github.com/bntjah/lancache/files/965476/lancache-osx.txt)

**Comment by nexusofdoom** [comment]
update had to use this config 

server {
    listen lancache-osx deferred default;
    server_name osx _;
    access_log /srv/lancache/logs/Access/osx.log main buffer=128k flush=1m;
    access_log /srv/lancache/logs/Keys/osx.log keys_slice buffer=128k flush=1m;
    error_log /srv/lancache/logs/Errors/osx.log;

    # Origin Node
    include lancache/resolver;
    location / {
        # Currently Origin:
        # * Blocks caching so we have to ignore Expires and Cache-Control.
        # * Puts sauth=<authkey> in the query string so we use $uri instead of $request_uri
        #   in the cache key.
        # * Uses a single archive file with range requests and refuses requests to download
        #   the entire file.
        #   To combat this we pass-through the Range headers and include the range to the
        #   cache key and allow caching of 206 responses.
        #proxy_bind x.x.x.x;
        proxy_ignore_headers Expires Cache-Control;
        proxy_hide_header ETag;
        proxy_cache_valid 206 90d;
        proxy_read_timeout 150;
        # Use Origin cache
        proxy_cache osx;
        include lancache/proxy-cache;
        include lancache/cache-slice;
    }
}

**Comment by nexusofdoom** [comment]
![p_20170428_182157_1_p](https://cloud.githubusercontent.com/assets/16519553/25551734/e75dd70c-2c4e-11e7-9241-5c6ef71c4de5.jpg)
![p_20170428_182300_1_p](https://cloud.githubusercontent.com/assets/16519553/25551736/ed2f6e5c-2c4e-11e7-8d72-41bd4a942361.jpg)
![p_20170428_182202_1_p](https://cloud.githubusercontent.com/assets/16519553/25551739/f441c938-2c4e-11e7-86e3-7b274d697b72.jpg)

**Comment by nexusofdoom** [comment]
added to github don't know if the lancache installer needs to be updated to make it install the added osx files.

**Comment by bntjah** [comment]
It does but will do it later on :-)
