### ISSUE TITLE
Bursty download performance

### ISSUE THREAD

**Issue by travispk** [bntjah/lancache#40]
Had a few staff notice at our last event that game downloads in Steam and Origin and maybe others are bursty.  They would get full speed 11MB/sec (100Mb port) down, and then it would drop to a few KB/sec for a bit, and then spike back up to full speed 11MB/sec.  I didn't have any available time to troubleshoot but wanted to raise this issue for more research.  Might be some optimizations tweaks with Nginx we need to add.

**Comment by bntjah** [comment]
I've seen this happen a few times in my test but on event it never occured so didn't look in to it...
But it does seem to be somewhere in the configs something

**Comment by fhibler** [comment]
This seems to be related to the http_range requests, as nginx seems to buffer first before it delivers the slices. There does not seem to be any proper passthrough of requests and background caching at the moment. Happy to suggestions?

**Comment by wendelj** [comment]
I saw something very similar to this when I only used a single gigabit port for our lancache. Looking at the port for our lancache in the LibreNMS realtime graph, it was pretty clear we were running into TCP global synchronization. Looking at the 5 min average graph didn't show anything unusual. Since I moved to a four gigabit port-channel, I haven't seen this issue anymore.

**Comment by travispk** [comment]
My lancache server has a 10Gb interface.  In my testing where I also saw the issue, was from a single computer with a 100Mb port.  So this would be out of the realm of global sync.

**Comment by travispk** [comment]
@nexusofdoom Do you think this performance could be improved with your discussion regarding tweaking proxy_buffering and other tweaks in that article you referenced in this issue?
https://github.com/bntjah/lancache/issues/37

As well, maybe we don't have enough allowed connections in Nginx?

I'm thinking we might have some large tweaks we can make with Nginx and Debian OS for improved performance.

**Comment by nexusofdoom** [comment]
i did apply some tweaks to my setup for games

I will update you with my settings and setup of hardware for lancache
server


<http://www.discoverpc.net>
Travus Elm - Support Specialist
travus@discoverpc.net discoverpc.NET <http://discoverpc.net/>, 1402 Tower
Ave., Superior, WI 54880
Local: (715) 398-6767 ::: Toll-free: (800) 721-1350
Mobile: (218) 260-1940 ::: Fax: (866) 704-3660
*Follow or like us on **Google+*
<https://plus.google.com/111445774308955992766/about?gl=us&hl=en>*, **Facebook
<http://www.facebook.com/pages/discoverpcNET-Computer-Solutions-Center/35471145348>,
**LinkedIn
<https://www.linkedin.com/in/travus-elm-73842268?trk=nav_responsive_tab_profile>*

PRIVILEGED AND CONFIDENTIAL COMMUNICATION This e-mail transmission, and any
documents, files or previous e-mail messages attached to it, may contain
confidential information that is legally privileged. If you are not the
intended recipient or a person responsible for delivering it to the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or use of any of the information contained in or attached to
this transmission is STRICTLY PROHIBITED. If you have received this
transmission in error, please: (1) immediately notify me by reply e-mail,
or by collect telephone call; and (2) destroy the original transmission and
its attachments without reading or saving in any manner
.

**Comment by travispk** [comment]
Awesome!  We did make a few tweaks to the master branch since I last used lancache at my last event.  Such as turning workers to auto and disabling ipv6.  I'm sure we got a lot more to go.

I also use XFS file system for the depots and logs, as I believe out of the box that FS has better performance than Ext4.

I see your name is Travus, my name is Travis as well...  I like your spelling better. 👍

**Comment by wendelj** [comment]
Now that I have a server with this setup using a 10Gb interface and a PC on a 100Mb port, I can say for sure that I don't see this same issue unless the disk/raid controller on the cache is running at 100% IO capacity. Is that something you've already looked at and eliminated as a possible cause?

**Comment by travispk** [comment]
I doubt It was.  I had (2) 1TB Samsung 850 Evos in RAID 0 with a PERC h710 in a Dell R620.

**Comment by n0xlf** [comment]
I rolled my own version of this for LANFest Colorado last time based on a whole bunch of different ones and did a single IP with the server_name directive in the confs, as mentioned in another thread.  As for pausing tweaks, I did a lot of playing around (best I could without having hundreds of clients connected) and found that these worked well:

----------------------------------------------------------------------

worker_processes auto;

events {
   worker_connections 8192;
   multi_accept on;
   use epoll;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

keepalive_requests 1000;
access_log /var/log/nginx/access.log combined buffer=128k flush=1m;

    resolver 75.75.75.75 75.75.76.76 ipv6=off;
    aio threads;
    aio_write on;
    types_hash_max_size 2048;
    directio 8m;
    directio_alignment 4k;
    output_buffers 2 1m;
    sendfile        on;
    tcp_nopush     on;
    tcp_nodelay    on;
    keepalive_timeout  30;

proxy_buffering    on;
proxy_buffer_size  128k;
proxy_busy_buffers_size 256k;
proxy_buffers 16 256k;
proxy_read_timeout 300;
proxy_request_buffering off;
proxy_max_temp_file_size 16384m;
proxy_temp_file_write_size 256k;
proxy_temp_path /cache/tmp/ 1 2;
proxy_cache_lock on;
gzip off;

----------------------------------------------------------------------

Some of those are already included but the others may be worth playing around with...

**Comment by bntjah** [comment]
I've read into the above and tried to integrate them as much as possible into the nginx.
If you see one that I missed do let me know; I'm closing it here
