### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by It0w** [bntjah/lancache#43]
please add

``./configure --with-http_sub_module --with-http_slice_module --with-http_ssl_module --with-file-aio --with-threads``

to Manual installation section

++

[emerg] "proxy_temp_path" directive is duplicate in /usr/local/nginx/conf/lancache/caches

**Comment by bntjah** [comment]
nice catch!

**Comment by bntjah** [comment]
should be fixed

**Comment by It0w** [comment]
Hi,

Please remove in /conf/nginx.conf

''proxy_temp_path /srv/lancache/data/tmp/ 1 2;''

and edit in /conf/lancache/caches 

''proxy_temp_path /srv/lancache/data/tmp/;''

to

''proxy_temp_path /srv/lancache/data/tmp/ 1 2;''

Thanks

**Comment by bntjah** [comment]
Thanks! Apparently didn't see these; should be ok now.

Thanks again for noticing!
