### ISSUE TITLE
Apple Cache not working.

### ISSUE THREAD

**Issue by saambd** [bntjah/lancache#46]
Configuration all OK but its can't write any file on apple folder.
mzstatic.com when set this to unbound apple store image can't show.
I can't see any image from here.
https://s.mzstatic.com/images/web/itunes_preview/itunespreview_en@2x.png

Also how many day to need cache Microsoft windows update? I already run it from tomorrow but windows update complete but its auto download from Microsoft site. which file it's caching i don't understand.

Please guys help me.

**Comment by nexusofdoom** [comment]
this is the running  config I have for my setup 

server {
    listen lancache-osx deferred default;
    server_name osx _;
    access_log /srv/lancache/logs/Access/osx.log main buffer=128k flush=1m;
    access_log /srv/lancache/logs/Keys/osx.log keys_slice buffer=128k flush=1m;
    error_log /srv/lancache/logs/Errors/osx.log;

    # Origin Node
    include lancache/resolver;
    location / {
        # Currently Origin:
        # * Blocks caching so we have to ignore Expires and Cache-Control.
        # * Puts sauth=<authkey> in the query string so we use $uri instead of $request_uri
        #   in the cache key.
        # * Uses a single archive file with range requests and refuses requests to download
        #   the entire file.
        #   To combat this we pass-through the Range headers and include the range to the
        #   cache key and allow caching of 206 responses.
        proxy_bind 192.168.30.105;
        proxy_ignore_headers Expires Cache-Control;
        proxy_hide_header ETag;
        proxy_cache_valid 206 90d;
        proxy_read_timeout 150;
        # Use Origin cache
        proxy_cache osx;
        include lancache/proxy-cache;
        include lancache/cache-slice;
    }
}

**Comment by nexusofdoom** [comment]
proxy_cache_path /srv/lancache/data/osx levels=2:2 keys_zone=osx:500m inactive=888d max_size=500000m loader_files=4000 loader_sleep=50ms loader_threshold=300ms;

**Comment by nexusofdoom** [comment]
## OSX Updates °|-lc-host-vint:6
        local-zone: "mzstatic.com." redirect
        local-data: "mzstatic.com. 600 IN A YOUR IP"
	local-zone: "swcdn.apple.com." redirect
        local-data: "swcdn.apple.com. 600 IN A YOUR IP"
        local-zone: "itunes-apple.com." redirect
        local-data: "itunes-apple.com. 600 IN A YOUR IP"
        local-zone: "swscan.apple.com." redirect
        local-data: "swscan.apple.com. 600 IN A YOUR IP"
        local-zone: "osxapps.itunes.apple.com." redirect
        local-data: "osxapps.itunes.apple.com. 600 IN A YOUR IP"

**Comment by nexusofdoom** [comment]
as far as windows , windows 10 and windows 7 download a little differently  i think that when downloading updates from windows 7 it take some time to download the files into cache vs windows 10 we just limit the amount it can pull down when downloading so it might take 3 hours or so for us to get it downloaded but once downloaded it will pull from the cache
