### ISSUE TITLE
Querying Info

### ISSUE THREAD

**Issue by TestCandidate** [bntjah/lancache#48]
Is this still working? 

I heard that lancache is having issues especially with league of legends. once an update is cached, other players can no longer connect to the league launcher.

I haven't tested myself. but I'd like to know if this repo is still maintained and if there are any issues that you are aware off that could cause any problems ?

Thanks

**Comment by bntjah** [comment]
Hi Testcandidate haven't tested it yet; as this is usually updated / tested a month or so before a lan we host.
Or upon receiving notice of something not working; so if I find the time I will try and test the League and post my findings here.

But usually there is always someone here trying to help out

**Comment by TestCandidate** [comment]
alright. 
I'm gonna try and test myself as well and report back.

But it's good to know that the repo is still being maintained.

**Comment by TestCandidate** [comment]
PS : would using Ubuntu 14  make any difference? or it has to be Debian ?

**Comment by bntjah** [comment]
I had bad experience with Ubuntu 14.* so hence using Debian as they're packages seems to be less experimental ;-)

**Comment by TestCandidate** [comment]
Noted. 

I'm gonna go ahead and test on Debian then. this way I'll have the best possible scenario.

Thanks.

**Comment by nexusofdoom** [comment]
Looks like it's working will need to test again once the download finish

**Comment by TestCandidate** [comment]
@nexusofdoom  thanks for the feedback.

Can you please explain the testing scenario?

As far as I know of, it works for a single user, but when there are cache data, for some reason, other users are not able to login anymore (the launcher wouldn't launch anymore. until the DNS (cache server) is removed. 


I'll test it too.

**Comment by TestCandidate** [comment]
I'm back to confirm the issue. 

although what's dazzling me is the different behavior it does over different tries.

at the moment, I launch the launcher, it shows the league logo and straightly disappear leaving no logs in the league logs folder.

whenever I remove the DNS IP from the network settings, the game works again. can't seem to figure out the issue

**Comment by nexusofdoom** [comment]
this weekend did a fresh os install on two computer and install lol it
downloaded from cache and I was able to login and play on both system. no
issues on my setup.


<http://www.discoverpc.net>
Travus Elm - Support Specialist
travus@discoverpc.net discoverpc.NET <http://discoverpc.net/>, 1402 Tower
Ave., Superior, WI 54880
Local: (715) 398-6767 ::: Toll-free: (800) 721-1350
Mobile: (218) 260-1940 ::: Fax: (866) 704-3660
*Follow or like us on **Google+*
<https://plus.google.com/111445774308955992766/about?gl=us&hl=en>*, **Facebook
<http://www.facebook.com/pages/discoverpcNET-Computer-Solutions-Center/35471145348>,
**LinkedIn
<https://www.linkedin.com/in/travus-elm-73842268?trk=nav_responsive_tab_profile>*

PRIVILEGED AND CONFIDENTIAL COMMUNICATION This e-mail transmission, and any
documents, files or previous e-mail messages attached to it, may contain
confidential information that is legally privileged. If you are not the
intended recipient or a person responsible for delivering it to the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or use of any of the information contained in or attached to
this transmission is STRICTLY PROHIBITED. If you have received this
transmission in error, please: (1) immediately notify me by reply e-mail,
or by collect telephone call; and (2) destroy the original transmission and
its attachments without reading or saving in any manner
.

**Comment by TestCandidate** [comment]
weird. any idea on how to troubleshoot this to try and guess what's happening ? 

I used the lc-installer on a clean debian Jessie.
steam seam to be working fine.

I tried copying a new clean installation of league. worked for a bit - then got the same issue when another computer started using it. 

and whenever I remove the server ip from dns config, it works again normally.

**Comment by TestCandidate** [comment]
Update:

after many tries, now I get this error:

![image](https://user-images.githubusercontent.com/22873773/28840709-7f502d34-7700-11e7-90b9-61ac4f48e913.png)

yet, still no logs... 

I need  to check what's going on on the server level. but i'm not sure where to start though 
is there any logs I should be checking there ? 

I have a client updating now. once it's done, i'm gonna try to clear the cache and re-try on this pc.

**Comment by TestCandidate** [comment]
on another note, 
if I run: 
`rm -R  /srv/lancache/data/riot/*`

the game works again. until there's data, then it  stops working :/ weird

**Comment by nexusofdoom** [comment]
is there a issue with the storage location on the server ? permissions ?

4 drwxr-xr-x  17 lancache lancache  4096 Jun 18 16:54 .
 4 drwxr-xr-x   4 lancache lancache  4096 Jun 18 16:54 ..
 4 drwxr-xr-x 258 lancache lancache  4096 Jun 24 16:17 arenanetworks
 4 drwxr-xr-x 258 lancache lancache  4096 Jul  1 15:41 blizzard
 4 drwxr-xr-x   2 lancache lancache  4096 Jun 18 16:54 gog
 4 drwxr-xr-x   2 lancache lancache  4096 Jun 18 16:54 hirez
 4 drwxr-xr-x   2 lancache lancache  4096 Jun 18 16:54 installs
 4 drwxr-xr-x 258 lancache lancache  4096 Jun 24 16:25 microsoft
 4 drwxr-xr-x 258 lancache lancache  4096 Jul 23 02:27 origin
 4 drwxr-xr-x 258 lancache lancache  4096 Jul  8 18:59 other
 4 drwxr-xr-x 258 lancache lancache  4096 Jul 23 10:47 riot
 4 drwxr-xr-x   2 lancache lancache  4096 Jun 18 16:54 sony
 4 drwxr-xr-x 258 lancache lancache  4096 Jun 18 19:59 steam
 4 drwxr-xr-x  48 lancache lancache  4096 Jul 23 10:44 tera
12 drwxr-xr-x   2 lancache lancache 12288 Aug  1 09:29 tmp
 4 drwxr-xr-x   2 lancache lancache  4096 Jun 18 16:54 uplay
 4 drwxr-xr-x  36 lancache lancache  4096 Jul 31 07:56 wargaming



<http://www.discoverpc.net>
Travus Elm - Support Specialist
travus@discoverpc.net discoverpc.NET <http://discoverpc.net/>, 1402 Tower
Ave., Superior, WI 54880
Local: (715) 398-6767 ::: Toll-free: (800) 721-1350
Mobile: (218) 260-1940 ::: Fax: (866) 704-3660
*Follow or like us on **Google+*
<https://plus.google.com/111445774308955992766/about?gl=us&hl=en>*, **Facebook
<http://www.facebook.com/pages/discoverpcNET-Computer-Solutions-Center/35471145348>,
**LinkedIn
<https://www.linkedin.com/in/travus-elm-73842268?trk=nav_responsive_tab_profile>*

PRIVILEGED AND CONFIDENTIAL COMMUNICATION This e-mail transmission, and any
documents, files or previous e-mail messages attached to it, may contain
confidential information that is legally privileged. If you are not the
intended recipient or a person responsible for delivering it to the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or use of any of the information contained in or attached to
this transmission is STRICTLY PROHIBITED. If you have received this
transmission in error, please: (1) immediately notify me by reply e-mail,
or by collect telephone call; and (2) destroy the original transmission and
its attachments without reading or saving in any manner
.

**Comment by TestCandidate** [comment]
I don't think so. 
Here's a screenshot

![image](https://user-images.githubusercontent.com/22873773/28841592-6d13a116-7703-11e7-8774-b54ec1786122.png)

**Comment by TestCandidate** [comment]
Added chmod -R 777 /srv/lancache/data/
still with the same dilemma.
this seem to be my problem:

`(  DEBUG)[21:29:51.491] RADS::Common::HTTPConnection::GetFile: ("/releases/live/system/rads_user_kernel.exe.version", "C:/Games/Riot Games/Riot/League of Legends/RADS/temp\TMPB64D.tmp", RETRY, 0x00000000)`

**Comment by bntjah** [comment]
@v3n did you happen to see any update that might have caused this?
I've seen this on our lan last year to but haven't been able to reproduce and apparently @TestCandidate is able to reproduce this problem...

**Comment by TestCandidate** [comment]
I'm going to try something that I'm not sure of. seem related to Unbound. 
I think we only need 
`l3cdn.riotgames.com`
Correct me if I'm wrong but for riot, I don't think we need the others.  maybe this could help solve the issue, eliminating the problem. or at least tighten the scope.

I'll let you guys know after some tests.

**Comment by bntjah** [comment]
Seems weird that this is related for Unbound as at our last event I had the same error but using Bind...
I only switched to unbound after the event

**Comment by TestCandidate** [comment]
Excuse my ambiguity. 
I didn't mean related to unbound itself. but i meant the configuration of unbound.
we have more hosts pointing locally than we need for caching.

i believe we only need the l3cdn.riotgames.com record 
i still don't have any test results tho. 
I'll let you guys know

**Comment by bntjah** [comment]
@TestCandidate I will test this is as well; since I'm currently rebuilding everything to test the range cache and trying to write down how to correctly use it...

**Comment by TestCandidate** [comment]
That would be awesome. 

The game has currently no issues. but I'm waiting for updates at the moment to see what would happen.

on the other hand, I faced some similar issues with overwatch. 
i added the header proxy_hide_header Etag; on nginx's config for blizzard (after comparing current conf with multiplay's one). 
not sure if it's a good idea tho. but I'll see how it goes. this way it get more fresh files i suppose instead of only checking for changes. this is probably a completely different thing anyway.

let me know how it goes and if there's anything I could help with.

**Comment by bntjah** [comment]
My current updates / tests / changes can be followed in the range_cache branch as I'm trying out the range cache that multiplay dropped so it might be that the proxy_hide_header is used with the range cache...

Will be interesting to see how I can pipe questions the patch uses in the installer. But those issues will be for when I get it working :-)

**Comment by TestCandidate** [comment]
proxy_hide_header doesn't seem related to range  or slicing. but yes. 
let's see where range_cache takes us.

**Comment by v3n** [comment]
Hey guys,

Not aware of anything on our side that would have changed around this (UserKernel.exe is actually deprecated with the release of the League client update and we haven't actually made changes to it in years).

This is most likely a CDN issue, what are the contents of `/releases/live/system/rads_user_kernel.exe.version`?

One workaround would be to ignore the `cache-control` header for that file and force it to `no-cache` if that file is getting corrupted for some reason.

Cheers,
Jonathan Howard // @v3n // summoner: Riot Venia

**Comment by bntjah** [comment]
@v3n thanks for the heads up; I will try your workaround and get back to you.
Might be something we did wrong as you said but I just wanted to make sure that from your end nothing really change.
And again thanks for taking the time to respond! 👍

**Comment by v3n** [comment]
Are you guys using SSL from the cache to the CDN? After thinking about it, it's possible that someone's modifying that file in-transit (which is why we introduced SSL in the first place).

**Comment by nexusofdoom** [comment]
For my weekly lans we have no issues with lol

**Comment by bntjah** [comment]
@v3n LOL seems to behave as it should; so no problem exists so far. I just have to check cache-control option you defined

**Comment by TestCandidate** [comment]
I'm gonna close this issue for now and re-setup.
If I face the same problem, I"LL BE BACK lol.
