### ISSUE TITLE
Clear Cache ?

### ISSUE THREAD

**Issue by Michael0786** [bntjah/lancache#49]
Hey,

Is there a way to clear the cache ?

And is there a way to change the size of the downloaded chunks ?, for some games the chunks are about 1m and for some around 100k.

Regards

**Comment by TestCandidate** [comment]
you can clear the cache by using:
rm -R /srv/lancache/data/*     -> this will clear all caches.
to clear cache for a  specific provider (riot for example) use:
rm -R /srv/lancache/data/riot/*
etc...

for the chunking, the file is located under /usr/local/nginx/conf/lancache/cache-slice
you can change the size to what your require.

**Comment by Michael0786** [comment]
Hey Test,

Thanks the clearing worked perfectly.

The chunking is already sat to 16M, but still the chunks inside steam is around 100K-200K. Any idea why ?

Regards

**Comment by bntjah** [comment]
@Michael0786 have a look at lancache/conf/lancache/caches line 7

**Comment by Michael0786** [comment]
Hey bntjah,

Which setting will change the chunk size ? im sorry im failing to see it.. 

proxy_cache_path /srv/lancache/data/steam levels=2:2 keys_zone=steam:500m inactive=120d max_size=5000000m loader_files=1000 loader_sleep=50ms loader_threshold=300ms;

I just tried downloading 2 games from Steam, both 700mb. 1 game was split into around 700 files, and the other one around 16000 files. Is that something Nginx/lancache does or is Steam ?

Regards

**Comment by TestCandidate** [comment]
I believe bntjah was pointing out the levels for the naming  / folders conventions (levels=2:2). 
here is out these levels affect the cache structure:

https://forum.nginx.org/read.php?2,2450,273132#msg-273132

**Comment by bntjah** [comment]
Indeed; trying to lead you in the right direction as for me how it works now is superb; but I know it differs for people...

**Comment by Michael0786** [comment]
Hey bntjah,

Ok i will try and change some settings here and there and see if i can achieve a higher download speed.

How fast can you download from the cache with your hardware setup ?

**Comment by bntjah** [comment]
Hi Michael0786,

I have to look it up but I got for sure around 750 mbps throughput
(average) and a maximum peak of 975 mbps (estimate)
This was on i5 2500k; Asus P8P67 Pro Rev 3.1; 16 GB Ram and ESXi (with
vm's) running on Samsung 840 Pro 256 GB.
My data was on 2 disks residing on 2 Samsung 850 Evo 500 GB wich were setup
as ZFS pool. Also teamed 2 or 3 nics (of the 5) for Lancache usage

If I would tweak the setup I would probably get a bith more speed but at
that time I had to host the pfsense on there as well.
As I didn't have dedicated hardware yet for pfsense, wich now I do...

2017-08-07 12:33 GMT+02:00 Michael0786 <notifications@github.com>:

**Comment by Michael0786** [comment]
Omg thats insane!

I got almost the same setup as you.

I5 -2500K Asus P8Z68 Gen3; 16 GB Ram
Debian on 120 GB Samsung SSD 
2x Samsung Evo 850 500 GB in ZFS pool (raid0) and i barely see
20-25 MB/S on all games, except one which saturates the gb net (95MB/S), and thats only because the downloaded files are in 1mb chunks.

Could you try and download "Legends of Ares" which is a free game, and post your results when downloaded from lancache ?..

**Comment by MastricX** [comment]
Careful with the MB vs Mb. Cache VM with a Fusion PCI-E and 10gbit NIC was giving clients about 70MB/s, 560mbits,  in steam. I don't think I tested it with a 10gbit client.

**Comment by bntjah** [comment]
Yeah, as I stated above its from memory so don't assume these to be facts; I do have a screenshot somewhere that I have to search for as I recall taking a screenshot of the terminal looking at the bandwith usage

**Comment by bntjah** [comment]
I am closing this issue; if its not resolved please let me know
