### ISSUE TITLE
Microsoft Update Issue?? lancache/pfSense

### ISSUE THREAD

**Issue by SilverDFlame** [bntjah/lancache#50]
Hey everyone! I'm having the same issues in my lancache as seen in #37. I see that as being marked as resolved, but even with the final microsoft.conf posted in there, I'm still having issues.

My topology for this is as follows:

```
Proxmox Virtual Env:        |------> switch (managed)  |-----> PCs
     VM1: Router (pfSense)
     VM2: Lancache (Ubuntu Server 17.04)            
```

I'm using pfSense's Unbound DNS resolver to filter and redirect to the lancache. This part is working for Steam/Blizzard/Arenanet/etc. I also see microsoft updates coming into lancache. It's when the microsoft updates start that things go bad. My DL speeds get slammed to capacity, and nothing is really seen getting passed back to the PCs on the LAN.

If I'm understanding the issue in #37, the ultimate resolution was to disable IPv6 for Unbound. But I'm not able to (or too dumb/tired to find the option to) disable that for the pfSense VM. Every time I make the change to unbound.conf and reboot or restart DNS, the unbound.conf gets wiped back to a default saved state. Near as I can tell this is a pfSense thing, and I need to change it in the Web-GUI. But like I said, I'm unable to find the option.

Any tips for the noob to get this working would be greatly appreciated!

**Comment by bntjah** [comment]
Hi SilverDFlame, I am rebuilding my entire setup so I will give this a test and will let you know if I run into it; otherwise I will have a search for it.
But perhaps @imac2009 knows from the top of his head where this option is sitting under

**Comment by SilverDFlame** [comment]
Awesome, thanks bntjah! So far everything else has been working great, and I've just commented out the Microsoft portion of the unbound.conf to keep the system up. I really appreciate all the work that's been put into this.

**Comment by bntjah** [comment]
I see something really similar happen with origin.
My download speed keeps going at around perhaps 3 mbps and my upload is just getting slammed all the way... and after a while origin timesout and then does nothing. So I'm looking in to this and then trying to replicate my solution to microsoft

**Comment by bntjah** [comment]
Sorry; didn't get around to updating this due to some training I had to follow; but I've seen a similar issue happen @ GnB (event from @imac2009) we redirected the Microsoft http to 127.0.0.1 as we were unable to pinpoint the cause... So will update here if we happen to find a solution to this as I couldn't find anything related to this in the logs... So will be trial and error

**Comment by travispk** [comment]
I had this exact issue at our last event in April this year.  However, since #37 was corrected, I have not seen it occur again.  I just had a 400 person event two weekends ago without an issues from lancache.  I think the Microsoft depot got up to 40GB of storage.  I even saw an attendee reinstall and completely patch a Windows 10 box during the event.

**Comment by bntjah** [comment]
Could be since I changed something in the config to make it more uniform compared to the other configs; so reset back to the config posted by @nexusofdoom

**Comment by nexusofdoom** [comment]
this is my current running config for widows updates 

"proxy_cache_use_stale updating;" was what was added .. 

---------------------------------------------------


server {
    listen lancache-microsoft deferred default;
    server_name microsoft _;
    access_log /srv/lancache/logs/Access/microsoft.log main buffer=128k flush=1m;
    access_log /srv/lancache/logs/Keys/microsoft.log keys_slice buffer=128k flush=1m;
    error_log /srv/lancache/logs/Errors/microsoft.log;

    # microsoft Node
    include lancache/resolver;

        proxy_cache_lock on;
    proxy_cache_lock_timeout 0s;
    proxy_cache_lock_age 3600s;
    proxy_cache_use_stale updating;

        location / {
        # Currently microsoft:
        # * Blocks caching so we have to ignore Expires and Cache-Control.
        # * Puts sauth=<authkey> in the query string so we use $uri instead of $request_uri
        #   in the cache key.
        # * Uses a single archive file with range requests and refuses requests to download
        #   the entire file.
        #   To combat this we pass-through the Range headers and include the range to the
        #   cache key and allow caching of 206 responses.
        proxy_bind x.x.x.x;
        proxy_ignore_headers Expires Cache-Control;
        proxy_hide_header ETag;
        proxy_cache_valid 206 90d;
        proxy_read_timeout 150;
        # Use microsoft cache
        proxy_cache microsoft;
        include lancache/proxy-cache;
        include lancache/cache-slice;
    }
}

**Comment by nexusofdoom** [comment]
just today added some more dns names for ms updates for the fall update 

     ## Microsoft Windows Updates °|-lc-host-vint:7
        local-zone: "windowsupdate.com." redirect
        local-data: "windowsupdate.com. 600 IN A "
        local-zone: "update.microsoft.com." redirect
        local-data: "update.microsoft.com. 600 IN A "
        local-zone: "windowsupdate.microsoft.com." redirect
        local-data: "windowsupdate.microsoft.com. 600 IN A "
        local-zone: "mp.microsoft.com." redirect
        local-data: "mp.microsoft.com. 600 IN A "
        local-zone: "wns.windows.com." redirect
        local-data: "wns.windows.com. 600 IN A "
        #local-zone: "dl.delivery.mp.micrsoft.com." redirect
        #local-data: "dl.delivery.mp.microsoft.com. 600 IN A "
        local-zone: "vortex-win.data.microsoft.com." redirect
        local-data: "vortex-win.data.microsoft.com. 600 IN A "
        local-zone: "cdn.content.prod.cms.msn.com." redirect
        local-data: "cdn.content.prod.cms.msn.com. 600 IN A "

**Comment by nexusofdoom** [comment]
the one above is for my work setup 

this is the one I have for my home setup just updated at my place tonight 

## Microsoft Windows Updates °|-lc-host-vint:7
        local-zone: "windowsupdate.com." redirect
        local-data: "windowsupdate.com. 600 IN A "
        local-zone: "dlassets.xboxlive.com." redirect
        local-data: "dlassets.xboxlive.com. 600 IN A "
        local-zone: "msxbassets.loris.llnwd.net." redirect
        local-data: "msxbassets.loris.llnwd.net. 600 IN A "
        local-zone: "xboxone.loris.llnwd.net." redirect
        local-data: "xboxone.loris.llnwd.net. 600 IN A "
        local-zone: "xboxone.vo.llnwd.net." redirect
        local-data: "xboxone.vo.llnwd.net. 600 IN A "
        local-zone: "images-eds.xboxlive.com." redirect
        local-data: "images-eds.xboxlive.com. 600 IN A 1"
        local-zone: "xbox-mbr.xboxlive.com." redirect
        local-data: "xbox-mbr.xboxlive.com. 600 IN A "
        local-zone: "assets1.xboxlive.com.nsatc.net." redirect
        local-data: "assets1.xboxlive.com.nsatc.net. 600 IN A "
        local-zone: "assets1.xboxlive.com." redirect
        local-data: "assets1.xboxlive.com. 600 IN A "
        local-zone: "assets2.xboxlive.com." redirect
        local-data: "assets2.xboxlive.com. 600 IN A"
        #local-zone: "cdn.content.prod.cms.msn.com." redirect
        #local-data: "cdn.content.prod.cms.msn.com. 600 IN A "
        local-zone: "mp.microsoft.com." redirect
        local-data: "mp.microsoft.com. 600 IN A "

**Comment by nexusofdoom** [comment]
more notes on that one domain 

https://blogs.technet.microsoft.com/windowsserver/2017/01/09/why-wsus-and-sccm-managed-clients-are-reaching-out-to-microsoft-online/

**Comment by nexusofdoom** [comment]
and it looks like more domains :-) 
https://xorcat.net/2017/09/01/high-throughput-microsoft-domains/

**Comment by nexusofdoom** [comment]
Rasheed explained how to set up that rule. An organization's proxy server should support HTTP RANGE requests for the following URLs:

.download.windowsupdate.com
.au.windowsupdate.com
.tlu.dl.delivery.mp.microsoft.com
With those HTTP RANGE request settings in place, just the "deltas," or the changed bits, for the applications will get delivered.

**Comment by BloodyIron** [comment]
So are Windows Updates now covered by these mentioned changes?

**Comment by SilverDFlame** [comment]
### Thanks All
I haven't taken the opportunity to implement the latest changes, and since I'm re-doing my entire setup anyways, my original question is no longer valid to me. (I'm running a completely new network stack)

Thanks again for everyone's input into all of this. I'm going to close this for now, as I believe that my original concerns have been addressed in the recent work being done by Bntjah/NexusofDoom.
