### ISSUE TITLE
Range_Cache Branch

### ISSUE THREAD

**Issue by bntjah** [bntjah/lancache#51]
So I've seen the range_cache module beeing dropped by multiplay and I'm finally able to test it.
Needless to say I will post my progress in the range cache branch so its experimental but any help would appreciated :-)

**Comment by TestCandidate** [comment]
I'd like to help. but I need more details on how to coordinate and what to help with

**Comment by bntjah** [comment]
Currently its just experimental; trying to write down what is necessary for getting everything compiled and then trying to cleanup the configs and integrate the range cache... And test what is better slice or range cache... So if you have an idea just drop it in here and we'll try and see where we land with it :-)

**Comment by TestCandidate** [comment]
Gonna do some readings, sum things up, and then see if there's anything useful to drop here.

**Comment by nexusofdoom** [comment]
this is what I had to do to get range_cache compiled into nginx 

pkg install GeoIP
/usr/local/bin/geoipupdate.sh
pkg install libgd

mkdir  "/usr/portbuild/www/nginx/work"


mkdir "/data/www/cache/installs"
mkdir"/data/www/logs/"


cd /usr/portbuild/www/nginx/work


nano /boot/defaults/loader.conf
#add to end of file 
 accf_http_load = "YES"


wget "https://codeload.github.com/wandenberg/nginx-push-stream-module/tar.gz/0.5.1?dummy=/wandenberg-nginx-push-stream-module-0.5.1_GH0.tar.gz"

tar zxvf "0.5.1?dummy=%2Fwandenberg-nginx-push-stream-module-0.5.1_GH0.tar.gz"





wget "http://labs.frickle.com/files/ngx_cache_purge-2.3.tar.gz"

tar zxvf "ngx_cache_purge-2.3.tar.gz"





wget "https://codeload.github.com/multiplay/nginx-range-cache/tar.gz/0.2?dummy=/multiplay-nginx-range-cache-0.2_GH0.tar.gz"

tar zxvf "0.2?dummy=%2Fmultiplay-nginx-range-cache-0.2_GH0.tar.gz"







./configure --add-module=/usr/portbuild/www/nginx/work/nginx-push-stream-module-0.5.1



./configure --add-module=/usr/portbuild/www/nginx/work/ngx_cache_purge-2.3



./configure --add-module=/usr/portbuild/www/nginx/work/nginx-range-cache-0.2



#./configure: error: the HTTP image filter module requires the GD library.

#wget "https://github.com/libgd/libgd/releases/download/gd-2.2.5/libgd-2.2.5.tar.gz"

#tar zxvf "gd-2.2.5/libgd-2.2.5.tar.gz"

#cd libgd-2.2.5

#./configure

#make 

#make install

or 


pkg install libgd






#cd to src location  then run 



   ./configure --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --user=www --group=www --modules-path=/usr/local/libexec/nginx --with-file-aio --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx/access.log --add-module=/usr/portbuild/www/nginx/work/ngx_cache_purge-2.3 --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --add-module=/usr/portbuild/www/nginx/work/nginx-range-cache-0.2 --with-http_realip_module --with-http_slice_module --with-http_stub_status_module --with-pcre --with-http_v2_module --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module

make 

make install

**Comment by TestCandidate** [comment]
@nexusofdoom 
Thank you for sharing!. 

But guys, i'm still having trouble understanding why are we going through all this? 

I couldn't find enough readings that show what does range_cache has to offer that the built in slice module doesn't? How is it better?
And what is the real issue we're trying to solve with it?

**Comment by nexusofdoom** [comment]
looks like more for windows updates 

Proxy servers must support HTTP 1.1 RANGE requests
BITS supports HTTP and HTTPS downloads and uploads and requires that the server support the HTTP 1.1 protocol. For downloads, the HTTP server's HEAD method must return the file size, and its GET method must support the Content-Range and Content-Length headers. BITS can use an HTTP/1.0 server as long as it meets the HEAD and GET method requirements (MIME headers must include the standard Content-Range and Content-Type headers plus a maximum of 180 bytes of other headers, and a maximum of two CR/LF characters may occur between the HTTP headers and the first boundary string).

ref 
https://technet.microsoft.com/en-us/library/cc720473%28v=ws.10%29.aspx

**Comment by TestCandidate** [comment]
oh okay. so no improvements for the gaming platforms? 
Anyway, as for now, what is the most stable version to use for a new setup in your opinion? I want to re-setup the whole thing again

**Comment by nexusofdoom** [comment]
this is what i am using at work every day still testing with the new windows 10 1709 fall creative update is pulling from new servers "tlu.dl.delivery.mp.microsoft.com" added to unbound.conf

----------------------

this is what is in nginx config for windows updates

map $upstream_http_content_length $flag_cache_empty {
default         0;
0               1;
}


server {
    listen lancache-microsoft deferred default;
    server_name microsoft _;
    access_log /srv/lancache/logs/Access/microsoft.log main buffer=128k flush=1m;
    access_log /srv/lancache/logs/Keys/microsoft.log keys_slice buffer=128k flush=1m;
    error_log /srv/lancache/logs/Errors/microsoft.log;

    # microsoft Node
    include lancache/resolver;

    proxy_cache_lock on;
    proxy_cache_lock_timeout 0s;
    proxy_cache_lock_age 3600s;
    proxy_cache_use_stale updating;

        location / {
        proxy_no_cache $flag_cache_empty;
        proxy_cache_bypass $flag_cache_empty;
        # Currently microsoft:
        # * Blocks caching so we have to ignore Expires and Cache-Control.
        # * Puts sauth=<authkey> in the query string so we use $uri instead of $request_uri
        #   in the cache key.
        # * Uses a single archive file with range requests and refuses requests to download
        #   the entire file.
        #   To combat this we pass-through the Range headers and include the range to the
        #   cache key and allow caching of 206 responses.
        #proxy_bind x.x.x.x;
        proxy_ignore_headers Expires Cache-Control;
        #proxy_hide_header ETag;
        proxy_cache_valid 206 90d;
        proxy_read_timeout 150;
        # Use microsoft cache
        proxy_cache microsoft;
        include lancache/proxy-cache;
        include lancache/cache-slice;
    }
}

**Comment by TestCandidate** [comment]
So if I understand correctly, the master branch is the one to use at the moment, I don't care much for the windows update. I'm looking for stability on the gaming platforms.

**Comment by brgerig** [comment]
I thought that the slice module still used upstream range requests, just different, normalized ranges than the client asks for. I haven't yet tested MS, but shouldn't that work?

**Comment by bntjah** [comment]
Cleaning up issues; closing this...
