### ISSUE TITLE
playstation 4 updates not cached

### ISSUE THREAD

**Issue by cyrianox** [bntjah/lancache#54]
i tried this, but still not working
Any idea ?
	## Sony test
        local-zone: "playstation.net." transparent
        local-zone: "dl.playstation.net." redirect
        local-data: "dl.playstation.net. 600 IN A lc-host-sony"
        local-zone: "km.playstation.net." redirect
        local-data: "km.playstation.net. 600 IN A lc-host-sony"

**Comment by muffeeee** [comment]
Try adding: 
```

local-zone: "sony.com." transparent
local-zone: "pls.patch.station.sony.com." redirect
local-data: "pls.patch.station.sony.com. 600 IN A lc-host-sony"
local-zone: "playstation.net." transparent
local-zone: "gs2.ww.prod.dl.playstation.net." redirect
local-data: "gs2.ww.prod.dl.playstation.net. 600 IN A lc-host-sony"
local-zone: "gs2.sonycoment.loris-e.llnwd.net." redirect
local-data: "gs2.sonycoment.loris-e.llnwd.net. 600 IN A lc-host-sony"

```

I have no idea if this will cache ps4 updates, however it did solve some issues with playstation not being cached at all during a LAN event.

**Comment by bntjah** [comment]
Added the dns muffeee posted to the unbound config.

Thanks muffeee
