### ISSUE TITLE
lancache/conf/vhosts-enabled/lancache-glyph.conf

### ISSUE THREAD

**Issue by Shazzer1951** [bntjah/lancache#63]
Again Naming is not consistant

server {
    listen lancache-**glyph** deferred default;
    server_name **sony** _;
    access_log /srv/lancache/logs/Access/glyph.log main buffer=128k flush=1m;
    access_log /srv/lancache/logs/Keys/glyph.log keys_range buffer=128k flush=1m;
    error_log /srv/lancache/logs/Errors/glyph.log;

    # Default Node
    include lancache/resolver;
    include lancache/cache-key-default;

    location / {
        # Some downloads are very large so we cache based on range to keep single downloads quick and hence ensure interactivity is good.
        proxy_bind lc-host-proxybind;
        #proxy_cache_valid 206 90d;
        proxy_cache glyph;
        proxy_read_timeout 150;
        include lancache/proxy-cache;
        include lancache/cache-range;
    }
}

**Comment by nexusofdoom** [comment]
so is this working? 
I see it's added in.

**Comment by Shazzer1951** [comment]
I can not get this lancache configuration to work. I have tried manual and the lc-installer......I went through and updated all the scripts etc. on my. The lancache service exits on a code 0......can't find any issues......

Also on the LC-INSTALLER I had to disable it pulling the current config as their are additions in the updated script and configurations it does not handle correctly.

**Comment by cyrianox** [comment]
Have you done all this steps :

1/ install a clean debian
2/ install unbound (and configure it using files from github :: you have to
modify files according to your network configuration)
3/ install nginx (and configure it using files from github :: you have to
modify files according to your network configuration)
4/ change your DNS (internet box) to point to your debian unbound server

it's not easy, but if you understand how unbound/nginx/router/dns works,
you can do it

Le mar. 24 oct. 2017 à 03:40, Shazzer1951 <notifications@github.com> a
écrit :

**Comment by bntjah** [comment]
@nexusofdoom I don't know; I copied the Sony config (hence the error that @Shazzer1951) pointed out, wich is now corrected but I don't have a glyph account; so I'm unable to test...

**Comment by nexusofdoom** [comment]
ok when i get time this week will give it a try.

thanks

**Comment by nexusofdoom** [comment]
manually added the files to my setup and test , still need to do more testing but it did pull down and cache the files 

-------------KEYS ---------------

/srv/lancache/logs/Keys/glyph.log
[25/Oct/2017:07:48:33 -0500] - REQUEST="glyph/ch5-live-client-patch//content/patchlive02/360754.manifest" - KEY="glyph/ch5-live-client-patch/content/patchlive02/360754.manifest -" - CACHE="MISS"
[25/Oct/2017:07:48:33 -0500] - REQUEST="glyph/ch5-live-client-patch//content/patchlive02/download.359889-360754.txt" - KEY="glyph/ch5-live-client-patch/content/patchlive02/download.359889-360754.txt -" - CACHE="MISS"
[25/Oct/2017:07:50:01 -0500] - REQUEST="glyph/ch5-live-client-patch//public/aa-live-us.txt" - KEY="glyph/ch5-live-client-patch/public/aa-live-us.txt -" - CACHE="HIT"
[25/Oct/2017:07:50:01 -0500] - REQUEST="glyph/ch5-live-client-patch//content/patchlive02/360754.manifest" - KEY="glyph/ch5-live-client-patch/content/patchlive02/360754.manifest -" - CACHE="HIT"
[25/Oct/2017:07:50:01 -0500] - REQUEST="glyph/ch5-live-client-patch//content/patchlive02/download.359889-360754.txt" - KEY="glyph/ch5-live-client-patch/content/patchlive02/download.359889-360754.txt -" - CACHE="HIT"
[25/Oct/2017:07:50:28 -0500] - REQUEST="glyph/ch5-live-client-patch//public/aa-live-us.txt" - KEY="glyph/ch5-live-client-patch/public/aa-live-us.txt -" - CACHE="HIT"
[25/Oct/2017:07:50:28 -0500] - REQUEST="glyph/ch5-live-client-patch//public/aa-live-us.txt" - KEY="glyph/ch5-live-client-patch/public/aa-live-us.txt -" - CACHE="HIT"
[25/Oct/2017:07:50:29 -0500] - REQUEST="glyph/ch5-live-client-patch//content/patchlive02/360754.manifest" - KEY="glyph/ch5-live-client-patch/content/patchlive02/360754.manifest -" - CACHE="HIT"
[25/Oct/2017:07:50:29 -0500] - REQUEST="glyph/ch5-live-client-patch//content/patchlive02/download.359889-360754.txt" - KEY="glyph/ch5-live-client-patch/content/patchlive02/download.359889-360754.txt -" - CACHE="HIT"
[25/Oct/2017:07:50:39 -0500] - REQUEST="glyph/ch5-live-client-patch//content/patchlive02/delta.359889-360754.0.pak?sha1=768a75928bd8abb2a64d829f6ceee376a6436261" - KEY="glyph/ch5-live-client-patch/content/patchlive02/delta.359889-360754.0.pak -" - CACHE="MISS"


-----------Access----------


10.0.5.9 - [25/Oct/2017:07:48:33 -0500] - REQUEST="GET /ch5-live-client-patch//content/patchlive02/360754.manifest HTTP/1.1" - REQUEST_URI="/ch5-live-client-patch//content/patchlive02/360754.manifest" - URI="/ch5-live-client-patch/content/patchlive02/360754.manifest" - STATUS="200" - BYTES="42502"
10.0.5.9 - [25/Oct/2017:07:48:33 -0500] - REQUEST="GET /ch5-live-client-patch//content/patchlive02/download.359889-360754.txt HTTP/1.1" - REQUEST_URI="/ch5-live-client-patch//content/patchlive02/download.359889-360754.txt" - URI="/ch5-live-client-patch/content/patchlive02/download.359889-360754.txt" - STATUS="200" - BYTES="474"
10.0.5.9 - [25/Oct/2017:07:50:01 -0500] - REQUEST="GET /ch5-live-client-patch//public/aa-live-us.txt HTTP/1.1" - REQUEST_URI="/ch5-live-client-patch//public/aa-live-us.txt" - URI="/ch5-live-client-patch/public/aa-live-us.txt" - STATUS="200" - BYTES="449"
10.0.5.9 - [25/Oct/2017:07:50:01 -0500] - REQUEST="GET /ch5-live-client-patch//content/patchlive02/360754.manifest HTTP/1.1" - REQUEST_URI="/ch5-live-client-patch//content/patchlive02/360754.manifest" - URI="/ch5-live-client-patch/content/patchlive02/360754.manifest" - STATUS="200" - BYTES="42435"
10.0.5.9 - [25/Oct/2017:07:50:01 -0500] - REQUEST="GET /ch5-live-client-patch//content/patchlive02/download.359889-360754.txt HTTP/1.1" - REQUEST_URI="/ch5-live-client-patch//content/patchlive02/download.359889-360754.txt" - URI="/ch5-live-client-patch/content/patchlive02/download.359889-360754.txt" - STATUS="200" - BYTES="407"
10.0.5.9 - [25/Oct/2017:07:50:28 -0500] - REQUEST="GET /ch5-live-client-patch//public/aa-live-us.txt HTTP/1.1" - REQUEST_URI="/ch5-live-client-patch//public/aa-live-us.txt" - URI="/ch5-live-client-patch/public/aa-live-us.txt" - STATUS="200" - BYTES="449"
10.0.5.9 - [25/Oct/2017:07:50:28 -0500] - REQUEST="GET /ch5-live-client-patch//public/aa-live-us.txt HTTP/1.1" - REQUEST_URI="/ch5-live-client-patch//public/aa-live-us.txt" - URI="/ch5-live-client-patch/public/aa-live-us.txt" - STATUS="200" - BYTES="449"
10.0.5.9 - [25/Oct/2017:07:50:29 -0500] - REQUEST="GET /ch5-live-client-patch//content/patchlive02/360754.manifest HTTP/1.1" - REQUEST_URI="/ch5-live-client-patch//content/patchlive02/360754.manifest" - URI="/ch5-live-client-patch/content/patchlive02/360754.manifest" - STATUS="200" - BYTES="42435"
10.0.5.9 - [25/Oct/2017:07:50:29 -0500] - REQUEST="GET /ch5-live-client-patch//content/patchlive02/download.359889-360754.txt HTTP/1.1" - REQUEST_URI="/ch5-live-client-patch//content/patchlive02/download.359889-360754.txt" - URI="/ch5-live-client-patch/content/patchlive02/download.359889-360754.txt" - STATUS="200" - BYTES="407"
10.0.5.9 - [25/Oct/2017:07:50:39 -0500] - REQUEST="GET /ch5-live-client-patch//content/patchlive02/delta.359889-360754.0.pak?sha1=768a75928bd8abb2a64d829f6ceee376a6436261 HTTP/1.1" - REQUEST_URI="/ch5-live-client-patch//content/patchlive02/delta.359889-360754.0.pak?sha1=768a75928bd8abb2a64d829f6ceee376a6436261" - URI="/ch5-live-client-patch/content/patchlive02/delta.359889-360754.0.pak" - ST
![img_20171025_075052](https://user-images.githubusercontent.com/16519553/32000801-822288aa-b95d-11e7-8331-b2d7e4977365.jpg)

**Comment by nexusofdoom** [comment]
notes from #59 


aa-update works for archeage, and only archeage.Correct DNS entry should by "dyn.triongames.com" as they use various subdomains of that for each of their games. Also, I've occasionally seen "update03.triongames.com"Those two DNS entries have made it so that every (free, at least) Glyph game gets cached for me.
--

**Comment by nexusofdoom** [comment]
corrected my testing server with the other domain names will keep an eye on it. and report back thanks

**Comment by bntjah** [comment]
Cleaning up issues; closing this...
