### ISSUE TITLE
Order in configs should be consistent

### ISSUE THREAD

**Issue by nagilum99** [bntjah/lancache#65]
To make it easier to adapt config for own network/s, config files should ahve the same order:

https://github.com/bntjah/lancache/blob/master/hosts
_lc-host-steam lancache-steam
lc-host-riot lancache-riot
lc-host-blizzard lancache-blizzard
lc-host-hirez lancache-hirez
lc-host-origin lancache-origin
lc-host-sony lancache-sony
lc-host-microsoft lancache-microsoft
lc-host-tera lancache-tera
lc-host-gog lancache-gog
lc-host-arena lancache-arenanetworks
lc-host-apple lancache-apple
lc-host-wargaming lancache-wargaming
lc-host-uplay lancache-uplay
lc-host-glyph lancache-glyph_

https://github.com/bntjah/lancache/blob/master/interfaces
_ # IP used for Steam caching
# IP used for Riot caching
# IP used for Blizzard caching
# IP used for Hirez caching
# IP used for Origin caching    
# IP used for Sony caching
# IP used for Microsoft caching
# IP used for Tera caching
# IP used for GOG caching
# IP used for ArenaNetworks caching
# IP used for WarGaming caching
# IP used for Uplay caching
# IP used for Uplay caching
# IP used for Glyph caching_
(shortened for clearness)

I've sumbitted a corrected interfaces file and send a pull request.

**Comment by bntjah** [comment]
Merged the pull and added it in the changelog.
This is mostly a one man job and doing with your help so if I mistakes just point them out and I'll be happy to solve them. If any one feels the want to help, let me know and I'll see with you what we can do together

**Comment by nagilum99** [comment]
We will run a LAN-Party next weekend in south/west germany with about 300 ppl. and hope we're able to benefit from the cache to save traffic.
I'll probably submit a small note to your readme, as I stubled over an old/removed nginx install, which cost me hours of debugging...
