### ISSUE TITLE
Help Wanted to maintain

### ISSUE THREAD

**Issue by bntjah** [bntjah/lancache#66]
If you feel like helping out as I'm a bith more occupied with work then before; do let me know through here or somewhere else and we'll try and figure out what we can do together

**Comment by brgerig** [comment]
I'm implementing your branch at my university. I'm doing as much testing as I possibly can, and tweaking as I find necessary. I can't commit to being an actual maintainer, but I can certainly provide feedback as I make modifications.

Also, I didn't clone the project, just downloaded it, so I can't push updates. (I don't use github very much...)

**Comment by ekhoury2000** [comment]
I can help with whatever u ask me too. Just that i am not much of a developper, but i can do my best and help more with implementations and tests since i am more into systems

**Comment by nexusofdoom** [comment]
do we want to make a facebook group page or google plus to keep in contact , or setup some time of monthly goals meeting or so on?

**Comment by ekhoury2000** [comment]
Sure i’m in

**Comment by bntjah** [comment]
I'm searching more for someone who can help me answer / figure out what is going wrong on when an issue pops up and able to test it.

And sure I'm available through Facebook. I'll post it later on

**Comment by nexusofdoom** [comment]
facebook group page url for lancache
https://www.facebook.com/groups/434599530274923/

**Comment by nexusofdoom** [comment]
any time.

**Comment by travispk** [comment]
How about a Discord server instead of a Facecrap group?

**Comment by Shazzer1951** [comment]
Yes please. I don’t use / have Facebook anymore.

Bill
LLAP
 
Confidentiality Notice: This email is for the sole use of the intended recipient and may contain
material that is confidential and protected by state and federal regulations. If you are not the
intended recipient please immediately delete it and contact the sender. Thank you.

**Comment by travispk** [comment]
I went ahead and created a Discord server if there is interest in using it.
https://discord.gg/haCGBMY

That can be linked in the Github repo for everyone to use. For those that don't know, Discord is like Slack, but for gamers and WAY better with text, voice, video and screen sharing. It's awesome for collaboration.

**Comment by bntjah** [comment]
I will hop on later on; once I get back to my home pc :-)

2017-10-27 0:41 GMT+02:00 travispk <notifications@github.com>:

**Comment by travispk** [comment]
The Discord server is starting to get a lot of usage.  Hop on if want to join in on the fun.
https://discord.gg/haCGBMY
