### ISSUE TITLE
Added Support for Wold of Warships

### ISSUE THREAD

**Issue by nexusofdoom** [bntjah/lancache#7]
DNS 
address=/*.wargaming.net.edgesuite.net/
address=/update.worldofwarships.com/
address=/wgusst-na.wargaming.net/
address=/tracker-na.wargaming.net/
address=/wg.gcdn.co/         -------------- main download locations
address=/update-v4r4h10x.worldofwarships.com/
address=/dl2.wargaming.net/

**Comment by nexusofdoom** [comment]
Game File needs to be updated WoWSLauncher.cfg to this
	<launcher_transport>2</launcher_transport>

form this 	<launcher_transport>3</launcher_transport>

**Comment by nexusofdoom** [comment]
#World Of Warships Updates
server {
        listen lancache-worldofwarships deferred default;
        server_name warships _;
        # DNS entries:
        # lancache-
        access_log /srv/lancache/logs/lancache-world-of-warships-access.log main buffer=128k flush=1m;
        access_log /srv/lancache/logs/lancache-world-of-warships-keys.log keys_default buffer=128k flush=1m;
        error_log /srv/lancache/logs/lancache-world-of-warships-error.log;

        # Default Node
        include lancache/resolver;
        #include lancache/cache-key-default;

        location / {
                proxy_cache worldofwarships;
                proxy_set_header Range $http_range;
                proxy_set_header If-Range $http_if_range;
                proxy_cache_key "$server_name$request_uri $http_range";
                proxy_cache_valid 206 90d;
                include lancache/proxy-cache;
        }
}

**Comment by nexusofdoom** [comment]
proxy_cache_path /srv/lancache/data/worldofwarships levels=2:2 keys_zone=worldofwarships:500m inactive=120d max_size=50000m loader_files=1000 loader_sleep=50ms loader_threshold=300ms;

**Comment by nexusofdoom** [comment]
it should work also for there other games from
wargaming.net
have not tested.  

will still need to edit the cfg file for the other games.

**Comment by nexusofdoom** [comment]
now tested with world of tanks and world of warships 
change name to wargaming added to conf vhost and caches

**Comment by nexusofdoom** [comment]
current config for wargaming 

World Of Warships Updates
server {
        listen lancache-wargaming  default;
        server_name wargaming _;
        # DNS entries:
        # lancache-
        access_log /srv/lancache/logs/lancache-wargaming-access.log main buffer=128k flush=1m;
        access_log /srv/lancache/logs/lancache-wargaming-keys.log keys_default buffer=128k flush=1m;
        error_log /srv/lancache/logs/lancache-wargaming-error.log;

    # Default Node
    include lancache/resolver;
    include lancache/cache-key-default;

        location / {
                # Currently Origin:
                # * Blocks caching so we have to ignore Expires and Cache-Control.
                # * Puts sauth=<authkey> in the query string so we use $uri instead of $request_uri
                #   in the cache key.
                # * Uses a single archive file with range requests and refuses requests to download
                #   the entire file.
                #   To combat this we pass-through the Range headers and include the range to the
                #   cache key and allow caching of 206 responses.
                proxy_ignore_headers Expires Cache-Control;
                proxy_set_header Range $http_range;
                proxy_set_header If-Range $http_if_range;
                proxy_cache_key "$server_name$uri $http_range";
                proxy_cache_valid 206 90d;
                proxy_cache_valid 200 90d;
                proxy_cache_valid 404 90d;
                #proxy_read_timeout 150
                # Use Origin cache
                proxy_cache wargaming;
                include lancache/proxy-cache;
        }
}

**Comment by nexusofdoom** [comment]
DNS testing 
issue with it getting the current patch 

this is the only one i am using now and will see hot it goes 

address=/wg.gcdn.co/ -------------- main download locations

**Comment by bntjah** [comment]
live in dev branch atm. Will port over to Production later this week
