### ISSUE TITLE
riot LOL updates again going over https not http 

### ISSUE THREAD

**Issue by nexusofdoom** [bntjah/lancache#76]
ticket open with riot 
TICKET #32772132 

#v3n

**Comment by nexusofdoom** [comment]
356    5.201120    209.197.3.7    10.0.4.17    TLSv1.2    1514    Server Hello
354    5.195297    209.197.3.7    10.0.4.17    TCP    60    [TCP Dup ACK 353#1] 443 → 54116 [ACK] Seq=1 Ack=518 Win=15872 Len=0
looks like the new update is now pulling all from HTTPS

**Comment by nexusofdoom** [comment]
![image](https://user-images.githubusercontent.com/16519553/33243887-6c913ec2-d2b3-11e7-8e08-89584e8ab490.png)

**Comment by bntjah** [comment]
@v3n please check from your end. Appears since last patch

**Comment by nexusofdoom** [comment]
Found 3 domains hosted on the same web server as 209.197.3.7.

blog.checkpoint.com l3cdn.riotgames.com www.fernandoike.com

**Comment by nexusofdoom** [comment]
last update from riot support 

SKELETOR
November 27th 2017, 8:41:31 pm
Hey there,

Dang, that sounds super frustrating. I'm going to send you over to the Tech team to see what's causing this problem, and hopefully solve the issue entirely. Just know that it might be a little bit, but they will get to you ASAP.

Skeletor
Riot Games Player Support

**Comment by nexusofdoom** [comment]
A lvl 99 Wizard (Riot Games Player Support)Nov 27, 7:34 PM PSTHey nexusofdoom,A lvl 99 Wizard has been summoned! I'm with Riot Player Support and I'll be here to help with any technical issues you have today.Thanks for writing in about this. Current there's no way to change the download type between http and https, but for your setup there's a few alternate solutions I came up with.You can completely patch League on one computer, then share then updated files across the network. Just launch League normally and let it patch, then go to C:\Riot GamesRight click on the League of Legends file. Click "Send to a compressed folder"You can take this zipped folder and share it with the rest of the computers on your network. They should be able to download it over wifi, or you can save it to a flash drive to send it to them.If you run into any issues with this process, you'll need to run a registry cleaner like Ccleaner. This will help clear out the partial files that wont get cleaned up simply by reinstalling.Keep in mind you'll have to go through this process for every patch that's released. However so far its the easiest way I've seen to share updates with multiple computers.If this gives you any issues, or if you have any questions be sure to let me know!Until then, have a great day!Best regards, A lvl 99 WizardRiot Games Player Support
--

**Comment by cyrianox** [comment]
Not good. We (network admin) can't spend so much time on this, it has to be
done automatically and transparent.

Le mar. 28 nov. 2017 à 07:43, nexusofdoom <notifications@github.com> a
écrit :

**Comment by nexusofdoom** [comment]
if we can add notes to the DEV channel for Riot maybe they will reply :-) 

https://boards.na.leagueoflegends.com/en/c/developer-corner/70pWABtr-quick-gameplay-thoughts-november-22?show=flat&page=8

**Comment by v3n** [comment]
Behavior from our end should be the same. None of the above information is helpful though.

What's the DNS entry for your cache server?

**Comment by nexusofdoom** [comment]
in wireshark it shows the client is pulling over 443 HTTPS
356 5.201120 209.197.3.7 10.0.4.17 TLSv1.2 1514 Server Hello
354 5.195297 209.197.3.7 10.0.4.17 TCP 60 [TCP Dup ACK 353#1] 443 → 54116 [ACK] Seq=1 Ack=518 Win=15872 Len=0
looks like the new update is now pulling all from HTTPS


DNS

 ## Riot Games °|-lc-host-vint:2
        local-zone: "riotgames.com." transparent
        local-zone: "l3cdn.riotgames.com." redirect
        local-data: "l3cdn.riotgames.com. 600 IN A 10.0.4.23"
        local-zone: "riotgamespatcher-a.akamaihd.net." redirect
        local-data: "riotgamespatcher-a.akamaihd.net. 600 IN A 10.0.4.23"
        local-zone: "riotgamespatcher-a.akamaihd.net.edgesuite.net." redirect
        local-data: "riotgamespatcher-a.akamaihd.net.edgesuite.net. 600 IN A 10.0.4.23"
        local-zone: "riotgamespatcher-b.akamaihd.net." redirect
        local-data: "riotgamespatcher-b.akamaihd.net. 600 IN A 10.0.4.23"
        local-zone: "riotgamespatcher-b.akamaihd.net.edgesuite.net." redirect
        local-data: "riotgamespatcher-b.akamaihd.net.edgesuite.net. 600 IN A 10.0.4.23"
        local-zone: "na.leagueoflegends.com." redirect
        local-data: "na.leagueoflegends.com. 600 IN A 10.0.4.23"

**Comment by nexusofdoom** [comment]
LeagueOfLegendsBaseNA.exeResolving l3cdn.riotgames.com (l3cdn.riotgames.com)... 209.197.3.7Connecting to l3cdn.riotgames.com (l3cdn.riotgames.com)|209.197.3.7

**Comment by nexusofdoom** [comment]
First part still pulls from the cache
![image](https://user-images.githubusercontent.com/16519553/33534104-1d8c9f0c-d86b-11e7-8404-2d9fa6fc19f3.png)

**Comment by nexusofdoom** [comment]
the 2nd screen is the one that was pulling updates over https on Nov 26th.
![image](https://user-images.githubusercontent.com/16519553/33534549-98547668-d86d-11e7-94c0-0188a0f81a23.png)

**Comment by nexusofdoom** [comment]
did the same today full uninstall and reinstall and it's no longer pulling from https
