### ISSUE TITLE
slow downloads

### ISSUE THREAD

**Issue by slyphe** [bntjah/lancache#77]
First of all ... thanks for your great work.

The Lan-Cache works great except the initial downloads. Seems to stuck at ~ 2.5MB/s @ a 12MB/s internet connection. 
![46875d2f3985d903f8e4c8f9c31aa901](https://user-images.githubusercontent.com/5421624/33651509-63e5e326-da66-11e7-8798-641154fb89b4.png)

I tried to tweak around but nothing really changed, tried several machines ... 
Gbit Ethernet
double HDD in Raid0 (~120mb/s)
6GB Ram ... etc
QuadCore blah .. 

but same result on an Rock64 aarch64 SBC 
with Gbit-Ethernet 
4GB Ram 
and an external HDD via usb 3.0

Is there any way to boost up the initial speed ?

**Comment by bntjah** [comment]
Is there a qos active on your gateway / router / source of internet?

**Comment by bntjah** [comment]
Cleaning up issues; closing this...

**Comment by fasa1977** [comment]
> Is there a qos active on your gateway / router / source of internet?

Hi @bntjah, in this post you asked if there is a gateway / router / source, in case it exist, what should be the problem, thanks !
