### ISSUE TITLE
ArenaNetworks Games

### ISSUE THREAD

**Issue by nexusofdoom** [bntjah/lancache#8]
working on getting Guildwars2 working it should work with there other games that they have 
testing now.. it looks like it will be good to go.

address=/.ArenaNetworks.com/x.x.x.x

**Comment by nexusofdoom** [comment]
#Arenanetworks Updates
server {
listen lancache-arenanetworks deferred default;
server_name arenanetworks _;
# DNS entries:
# lancache-
access_log /srv/lancache/logs/lancache-arenanetworks-access.log main buffer=128k flush=1m;
access_log /srv/lancache/logs/lancache-arenanetworks-keys.log keys_default buffer=128k flush=1m;
error_log /srv/lancache/logs/lancache-arenanetworks-error.log;

    # Default Node
    include lancache/resolver;
    #include lancache/cache-key-default;

    location / {
            proxy_cache arenanetworks;
            proxy_set_header Range $http_range;
            proxy_set_header If-Range $http_if_range;
            proxy_cache_key "$server_name$request_uri $http_range";
            proxy_cache_valid 206 90d;
            include lancache/proxy-cache;
    }
}

**Comment by nexusofdoom** [comment]
current config 
#Arenanetworks Updates
server {
        listen lancache-arenanetworks deferred default;
        server_name arenanetworks _;
        # DNS entries:
        # lancache-
        access_log /srv/lancache/logs/lancache-arenanetworks-access.log main buffer=128k flush=1m;
        access_log /srv/lancache/logs/lancache-arenanetworks-keys.log keys_default buffer=128k flush=1m;
        error_log /srv/lancache/logs/lancache-arenanetworks-error.log;

    # Default Node
    include lancache/resolver;
    include lancache/cache-key-default;

        location / {
                # Currently Origin:
                # * Blocks caching so we have to ignore Expires and Cache-Control.
                # * Puts sauth=<authkey> in the query string so we use $uri instead of $request_uri
                #   in the cache key.
                # * Uses a single archive file with range requests and refuses requests to download
                #   the entire file.
                #   To combat this we pass-through the Range headers and include the range to the
                #   cache key and allow caching of 206 responses.
                proxy_ignore_headers Expires Cache-Control;
                proxy_set_header Range $http_range;
                proxy_set_header If-Range $http_if_range;
                proxy_cache_key "$server_name$uri $http_range";
                proxy_cache_valid 200 120d;
                proxy_read_timeout 150;
                # Use Origin cache
                proxy_cache arenanetworks;
                include lancache/proxy-cache;
        }
}

**Comment by bntjah** [comment]
integrated into development / master branch
