### ISSUE TITLE
Typo in interfaces file

### ISSUE THREAD

**Issue by BloodyIron** [bntjah/lancache#83]
In the interfaces file for :15, 16 and 17, you have "eth0" when I'm pretty sure it should be "lc-host-vint".

**Comment by BloodyIron** [comment]
Also, the readme.md needs to be updated with this correction too (the instructions at the root reflect the old typo).

**Comment by nexusofdoom** [comment]
eth0 for manual install is correct if you are not using the installer.sh

**Comment by BloodyIron** [comment]
Um, but the manual install steps talk about cloning the configs from the repo, and I'm rather sure that would lead to a mismatch between what's declared in the interfaces file, and what's in the conf files. I mean, I may be missing a detail here, but that's what I'm seeing.

**Comment by nexusofdoom** [comment]
in the instructions I do not see if pulling the interface files into the location it needs to be in.

**Comment by nexusofdoom** [comment]
4) Add the virtual interfaces (used for caching in nginx) to /etc/network/interfaces

and under that it shows what needs to be in that file.

and down at the bottom you need to put in your ip information of your network setup.
15.1) Replace the interfaces: section with the normal ip (not the virtual ones)
15.2) Replace all A records with the appropriate IPs (the virtual IPs for the appropriate caching service)

**Comment by BloodyIron** [comment]
Ack, I think you're right, I didn't quite put the pieces together, whoops!

**Comment by bntjah** [comment]
Cleaning up issues that are possibly no longer relevant. Closing this...
