### ISSUE TITLE
Cache Epic Download Content

### ISSUE THREAD

**Issue by mfairouz** [bntjah/lancache#86]
dear, 
please can you help add Epic Games to cache server as they r using https and we are unable to cache download content using the provided project. 

i know that u r trying to avoid any configuration on the client side, but at least if there is any solution 4 now thats will be great as Epic games become popular here and without cache their updates its a big headache. 

appreciate your support. 
thanks

**Comment by nexusofdoom** [comment]
have not looked at this much since it's https
you could try and setup your own ssl cert nginx but then you would have to install a cert on all clients pc's
other issues will the epic client like that cert.

**Comment by fasa1977** [comment]
Hi @nexusofdoom any updates about EPIC games? as @mfairouz says, for now we can make some client side configurations, but, how? thanks in advance.

**Comment by nexusofdoom** [comment]
no real news on my side. not sure where you would edit the client side to do so. sorry

**Comment by KiNGKiMO** [comment]
I also would like to know if there are any news yet, need to cache Fortnite game.

Thanks.

**Comment by hasankaheil4** [comment]
any updates ?
Thanks.

**Comment by bntjah** [comment]
None so far; as Epic still sends it traffic on HTTPS with a signed cert... And we are trying to keep it so that our clients dont need to install a CERT on their PC...

Closing this untill anything changes in the future from EPIC
