### ISSUE TITLE
Hi-Rez Studios games aren't cached

### ISSUE THREAD

**Issue by chong601** [bntjah/lancache#88]
The existing hostname entry for Hi-Rez Studios (hirez.http.internapcdn.net) isn't in use anymore (returns NXDOMAIN).

With that, none of Hi-Rez Studios games are being cached on lancache.

**Comment by nexusofdoom** [comment]
do you have the hosts names needed? 
I might have time this weekend to look into it.

**Comment by nexusofdoom** [comment]
I sent a email to technicalissues@hirezstudios.com asking to list the host names needed for updates. 
will see if they respond before I get a chance to look at it.

**Comment by chong601** [comment]
So, after hours of WireShark-ing, here's the list of hostnames that is observed during downloads:
```
discovery.hirez.net (looks to be authentication related, HTTPS only)
lwcdn.hi-rezgame.net
cdn.hi-rez.com
cdn2hi-rezgame.akamaized.net
hirez.vo.llnwd.net
cds.q6u4m8x5.hwcdn.net
ad753f1968.site.internapcdn.net (which resilves to cdce.sin002.internap.com)
```
The last one from Internap seems to be regional servers (I'm located at SEA)

**Comment by bntjah** [comment]
Will implement these later on
