### ISSUE TITLE
Daemon files not up to date?

### ISSUE THREAD

**Issue by Wooza** [bntjah/lancache#96]
Hello,
first of all, thank you for this awesome project :)
Now for my issue:
I set up a completely minimal debian 9.4.0, configured a static IP and followed all steps in your checklist.
I think I did everything right, but so far only unbound is running and resolves the specified domains correctly.

I checked all the files and found that the "lancache/init.d/lancache" file pointed to the wrong location of the nginx executable, because the real one resides in "/usr/local/sbin/nginx" and not in
> DAEMON=/usr/local/nginx/sbin/nginx

I also found the two files "nginx" and "sniproxy" in "lancache/init.d/" which seem to be pointing to the correct locations for nginx aswell as for sniproxy but weren't mentioned in the guide.

Unfortunately I only know very basic stuff about debian and don't know how to set up these two files correctly. I would be very thankful if you could provide instructions on how to set these two files or update the guide accordingly.

Best regards
Wooza

**Comment by nexusofdoom** [comment]
sorry I have not used the /etc/init.d/lancache I just use the unbound, sniproxy and nginx 
I can update the location in lancache to look at the new locations needed for Debain 9.X

**Comment by nexusofdoom** [comment]
are you using the PDF or the Google drive doc for installing?

**Comment by Wooza** [comment]
There is a pdf or a google doc? I just used the guide from the readme.md. I have not found any mentions of a pdf or a google doc in this repo. Could you provide links for those?
Also thanks for the fast answer.

**Comment by nexusofdoom** [comment]
log  in to discordapp 
I have attached pdf in there,

**Comment by Wooza** [comment]
I am sorry if I have to ask again but what is the address of the discord server?

**Comment by nexusofdoom** [comment]
https://discordapp.com/channels/373160397349322762/373526892533252106

**Comment by Wooza** [comment]
I really dont want to bug you or embarass myself but I cant seem to access the channel that you posted :(

**Comment by nexusofdoom** [comment]
try this one 
Invite Link https://discord.gg/haCGBMY

**Comment by Wooza** [comment]
Thanks, I hope I can figure it out on my own from here

**Comment by bntjah** [comment]
@nexusofdoom we might need to update the readme accordingly to your PDF?

2018-03-26 23:00 GMT+02:00 Wooza <notifications@github.com>:

**Comment by nexusofdoom** [comment]
maybe this weekend we can take a look at it.
